-- Migration 037: Risk Assessment Module — Phase 1 schema.
--
-- Implements ISO 45001 6.1 + Cal/OSHA T8 §3203 IIPP hazard-evaluation
-- requirements. The five tables in this migration form the data spine:
--
--   risks                — the system of record for every identified
--                          OH&S risk in the org (ISO 45001 6.1.2.2).
--   controls_library     — tenant-scoped catalog of controls keyed by
--                          hierarchy level, drives the "suggested
--                          controls" UI in the wizard (ISO 45001 8.1.2).
--   risk_controls        — n:m link between risks and controls.
--                          Replaces the PDD's `controls jsonb` sketch
--                          so we can query "give me every engineering-
--                          control coverage across the register"
--                          without JSON path queries.
--   risk_reviews         — review history per risk (PDD §6.3 cadence).
--   risk_attachments     — supporting documents (SDSs, training,
--                          calibration certs, etc. per PDD §13.3).
--
-- Audit-log table + triggers + PPE-alone enforcement + risk-number
-- generation + RLS policies are split across migrations 038–040 to
-- keep each migration focused and reviewable.
--
-- Multi-tenancy: every table carries `tenant_id` NOT NULL. RLS lands
-- in 040.
--
-- Idempotent — guarded with `if not exists` / `do $$ ... $$` blocks.
-- Re-running is a no-op.

begin;

-- ──────────────────────────────────────────────────────────────────────────
-- 1. risks — the register
-- ──────────────────────────────────────────────────────────────────────────
--
-- Generated columns (`inherent_score`, `inherent_band`,
-- `residual_score`, `residual_band`) keep the scoring math
-- authoritative on the DB side. The TypeScript engine in
-- packages/core/src/risk.ts produces the same values for the wizard's
-- live preview but never writes them — the DB does. This guarantees
-- a single source of truth for the matrix logic; if a future
-- migration changes thresholds, every existing row reflects the
-- change without an app-layer backfill.
--
-- Band thresholds (ISO 45001 / PDD §4.5):
--   1–3   → 'low'
--   4–6   → 'moderate'
--   8–12  → 'high'
--   15–25 → 'extreme'
-- Note that score=7 is not reachable from the 5x5 grid (only
-- 1×1..5×5 products), so the case statement handles 4-6 → moderate
-- and ≥8 → high without an off-by-one risk.

create table if not exists public.risks (
  id                       uuid not null primary key default gen_random_uuid(),
  tenant_id                uuid not null references public.tenants(id) on delete cascade,
  -- Auto-generated by the trigger in migration 039. Format:
  -- RSK-{year}-{4-digit-tenant-sequence}, e.g. RSK-2026-0042. Unique
  -- within a tenant; collision-free across tenants because the
  -- sequence resets per (tenant_id, year).
  risk_number              text,
  title                    text not null,
  description              text not null,

  -- Hazard taxonomy from PDD §5.2 + ISO 45001 6.1.2.1 (psychosocial
  -- is required by the standard, not optional).
  hazard_category          text not null check (hazard_category in (
    'physical','chemical','biological','mechanical','electrical',
    'ergonomic','psychosocial','environmental','radiological')),

  -- How this risk got identified (PDD §5.3). 'other' is a soft
  -- escape hatch for sources we haven't categorized yet.
  source                   text not null check (source in (
    'inspection','jsa','incident','worker_report','audit','moc','other')),
  -- Soft FK — not a real FK. The source could be a JSA, an incident,
  -- an inspection, etc. — different tables, possibly added in
  -- different migrations. Application code resolves the reference
  -- using the `source` discriminator. See plan §"Soft FK".
  source_ref_id            uuid,

  location                 text,                                  -- free-form for Phase 1
  process                  text,
  activity_type            text not null check (activity_type in (
    'routine','non_routine','emergency')),

  -- Who is exposed. JSONB shape:
  --   { "workers": true, "contractors": false, "visitors": false, "public": false }
  -- Defaults to all-false; the wizard fills it in.
  affected_personnel       jsonb not null default '{}'::jsonb,
  exposure_frequency       text not null check (exposure_frequency in (
    'continuous','daily','weekly','monthly','rare')),

  -- Inherent risk — score with no controls applied.
  inherent_severity        int not null check (inherent_severity   between 1 and 5),
  inherent_likelihood      int not null check (inherent_likelihood between 1 and 5),
  inherent_score           int generated always as (inherent_severity * inherent_likelihood) stored,
  inherent_band            text generated always as (
    case
      when inherent_severity * inherent_likelihood <= 3  then 'low'
      when inherent_severity * inherent_likelihood <= 6  then 'moderate'
      when inherent_severity * inherent_likelihood <= 12 then 'high'
      else                                                    'extreme'
    end
  ) stored,

  -- Residual risk — score after planned/implemented controls. Both
  -- nullable because the wizard captures inherent first, then
  -- controls, then residual. Once both are set, the generated
  -- columns produce non-null scores.
  residual_severity        int check (residual_severity   is null or residual_severity   between 1 and 5),
  residual_likelihood      int check (residual_likelihood is null or residual_likelihood between 1 and 5),
  residual_score           int generated always as (
    case
      when residual_severity is null or residual_likelihood is null then null
      else residual_severity * residual_likelihood
    end
  ) stored,
  residual_band            text generated always as (
    case
      when residual_severity is null or residual_likelihood is null then null
      when residual_severity * residual_likelihood <= 3  then 'low'
      when residual_severity * residual_likelihood <= 6  then 'moderate'
      when residual_severity * residual_likelihood <= 12 then 'high'
      else                                                    'extreme'
    end
  ) stored,

  -- ISO 45001 8.1.2 + OSHA 1910.132(a) require higher-level controls
  -- before PPE. The trigger in migration 039 enforces "PPE alone is
  -- not allowed when inherent_score >= 8 unless this column has a
  -- documented justification". UI also enforces in the wizard for
  -- early feedback; the DB trigger is the auditor-verifiable
  -- backstop.
  ppe_only_justification   text,

  status                   text not null default 'open' check (status in (
    'open','in_review','controls_in_progress','monitoring','closed','accepted_exception')),

  -- Review cadence per PDD §6.3 (90/180/365/730 days by band). The
  -- review-cron in slice 4 reads next_review_date.
  next_review_date         date,
  last_reviewed_at         timestamptz,
  last_reviewed_by         uuid references auth.users(id),

  -- Single accountable person per ISO 45001 5.3 + IIPP §3203(a)(1).
  assigned_to              uuid references auth.users(id),
  reviewer                 uuid references auth.users(id),
  approver                 uuid references auth.users(id),

  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  created_by               uuid not null references auth.users(id),
  updated_by               uuid references auth.users(id),

  unique (tenant_id, risk_number)
);

create index if not exists idx_risks_tenant            on public.risks(tenant_id);
create index if not exists idx_risks_tenant_status     on public.risks(tenant_id, status) where status <> 'closed';
create index if not exists idx_risks_tenant_band       on public.risks(tenant_id, residual_band) where residual_band is not null;
create index if not exists idx_risks_next_review       on public.risks(tenant_id, next_review_date) where status not in ('closed','accepted_exception');
create index if not exists idx_risks_assigned          on public.risks(assigned_to) where assigned_to is not null;

-- ──────────────────────────────────────────────────────────────────────────
-- 2. controls_library — tenant-scoped catalog of available controls
-- ──────────────────────────────────────────────────────────────────────────
--
-- Hierarchy levels per ISO 45001 8.1.2:
--   elimination     — remove the hazard entirely (highest weight)
--   substitution    — replace with a safer alternative
--   engineering     — guards, ventilation, isolation, interlocks
--   administrative  — procedures, training, signage, rotation
--   ppe             — gloves, respirators, hearing protection (lowest)
--
-- Tenant-scoped so a customer can extend with industry-specific
-- entries (cannabis SOP, oil & gas SIMOPS additions, etc. per
-- PDD §18). Slice 3 will seed each new tenant with a starter library
-- of ~30 baseline controls.

create table if not exists public.controls_library (
  id               uuid not null primary key default gen_random_uuid(),
  tenant_id        uuid not null references public.tenants(id) on delete cascade,
  hierarchy_level  text not null check (hierarchy_level in (
    'elimination','substitution','engineering','administrative','ppe')),
  name             text not null,
  description      text,
  -- Optional pointer to the regulatory clause this control addresses
  -- (e.g. 'OSHA 1910.95(b)(1)' for hearing conservation engineering
  -- controls). Free-form for v1; slice 4 may move this into a normalized
  -- legal_requirements table.
  regulatory_ref   text,
  -- Hazard categories this control is most relevant for. Powers the
  -- "suggested controls" filter in the wizard.
  applicable_categories jsonb not null default '[]'::jsonb,
  active           boolean not null default true,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  created_by       uuid references auth.users(id),
  updated_by       uuid references auth.users(id),
  unique (tenant_id, hierarchy_level, name)
);

create index if not exists idx_controls_library_tenant_level
  on public.controls_library(tenant_id, hierarchy_level) where active = true;

-- ──────────────────────────────────────────────────────────────────────────
-- 3. risk_controls — n:m link between risks and controls
-- ──────────────────────────────────────────────────────────────────────────
--
-- One row per (risk, control). status tracks the implementation
-- lifecycle (planned → implemented → verified). The DB-side
-- PPE-alone trigger (migration 039) reads from this table to
-- validate that a high-inherent risk has at least one non-PPE
-- control OR the risk row carries a ppe_only_justification.
--
-- We also support free-text controls (control_id NULL + custom_name)
-- so a wizard user can enter an ad-hoc control without forcing them
-- to add it to the library first. The DB still enforces the
-- hierarchy_level on every row.

create table if not exists public.risk_controls (
  id                  uuid not null primary key default gen_random_uuid(),
  tenant_id           uuid not null references public.tenants(id) on delete cascade,
  risk_id             uuid not null references public.risks(id) on delete cascade,
  -- Either link to a library entry or carry a custom name.
  control_id          uuid references public.controls_library(id),
  custom_name         text,
  hierarchy_level     text not null check (hierarchy_level in (
    'elimination','substitution','engineering','administrative','ppe')),
  status              text not null default 'planned' check (status in (
    'planned','implemented','verified','superseded')),
  notes               text,
  implemented_at      timestamptz,
  verified_at         timestamptz,
  verified_by         uuid references auth.users(id),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  created_by          uuid not null references auth.users(id),
  updated_by          uuid references auth.users(id),
  -- Either the library link or the custom name must be present.
  -- Both being NULL means the row carries no information about
  -- the control itself and would render as a blank entry in the
  -- wizard's control list.
  check (control_id is not null or custom_name is not null)
);

create index if not exists idx_risk_controls_risk    on public.risk_controls(risk_id);
create index if not exists idx_risk_controls_tenant  on public.risk_controls(tenant_id);
-- Powers the "% of risks with engineering controls" KPI in slice 4.
create index if not exists idx_risk_controls_tenant_level
  on public.risk_controls(tenant_id, hierarchy_level);

-- ──────────────────────────────────────────────────────────────────────────
-- 4. risk_reviews — review history per risk
-- ──────────────────────────────────────────────────────────────────────────
--
-- Cadence per PDD §6.3 (90/180/365/730 days by band). Plus
-- automatic re-review triggered by: incident, MOC, audit finding,
-- regulatory change, worker report. Each review captures the
-- reviewer, what changed (re-scored? new control? closed?), and
-- comments — supports the ISO 45001 9.1 monitoring requirement.

create table if not exists public.risk_reviews (
  id              uuid not null primary key default gen_random_uuid(),
  tenant_id       uuid not null references public.tenants(id) on delete cascade,
  risk_id         uuid not null references public.risks(id) on delete cascade,
  reviewed_at     timestamptz not null default now(),
  reviewed_by     uuid not null references auth.users(id),
  -- 'cadence' = scheduled review on next_review_date.
  -- 'incident' / 'moc' / 'audit' / 'worker_report' / 'regulatory' =
  -- triggered by an external event linking to that source.
  trigger         text not null check (trigger in (
    'cadence','incident','moc','audit','worker_report','regulatory','manual')),
  -- Snapshot of the scores at review time so a later re-score
  -- doesn't lose the historical context.
  inherent_score_at_review  int,
  residual_score_at_review  int,
  outcome         text not null check (outcome in (
    'no_change','rescored','controls_updated','closed','escalated')),
  notes           text,
  created_at      timestamptz not null default now()
);

create index if not exists idx_risk_reviews_risk on public.risk_reviews(risk_id, reviewed_at desc);

-- ──────────────────────────────────────────────────────────────────────────
-- 5. risk_attachments — supporting documents
-- ──────────────────────────────────────────────────────────────────────────
--
-- PDD §13.3 lists SDSs, calibration certs, training records,
-- inspection forms, JSAs, PPE assessments (1910.132(d)), permits.
-- Files live in Supabase Storage; this table is just the metadata
-- pointer. Storage RLS already enforces tenant scoping
-- (migration 033).

create table if not exists public.risk_attachments (
  id              uuid not null primary key default gen_random_uuid(),
  tenant_id       uuid not null references public.tenants(id) on delete cascade,
  risk_id         uuid not null references public.risks(id) on delete cascade,
  storage_path    text not null,                              -- key in loto-photos / future risk-attachments bucket
  file_name       text not null,
  file_size_bytes bigint,
  content_type    text,
  attachment_type text check (attachment_type in (
    'sds','jsa','training_record','calibration_cert','inspection',
    'ppe_assessment','permit','photo','other')),
  description     text,
  uploaded_at     timestamptz not null default now(),
  uploaded_by     uuid references auth.users(id)
);

create index if not exists idx_risk_attachments_risk on public.risk_attachments(risk_id);

-- Reload PostgREST schema so the new tables show up in the API.
notify pgrst, 'reload schema';

commit;
