-- Migration 042: Near-Miss Reporting Module — schema + audit log + RLS.
--
-- A near-miss is "an unplanned event that did not result in injury,
-- illness, or damage — but had the potential to do so" (OSHA, NSC).
-- Capturing them feeds the leading-indicator signal that drives
-- ISO 45001 9.1 monitoring + Cal/OSHA T8 §3203 IIPP investigation
-- requirements. Distinct from the `risks` table:
--
--   risks         — durable hazards in the register (ongoing
--                   exposures, evaluated and controlled).
--   near_misses   — point-in-time events that nearly caused harm.
--                   Each near-miss may *escalate* to a risk register
--                   entry via the optional `linked_risk_id` FK; the
--                   escalation API in slice 2 will create that link.
--
-- Single migration: schema + audit log + RLS + report-number
-- generator. Smaller surface than risk-assessment (one user-facing
-- table vs five) so we don't need the migration split.
--
-- Multi-tenancy: tenant_id NOT NULL on every table; RLS uses the
-- standard active_tenant_id() + current_user_tenant_ids() pattern.
--
-- Idempotent — guarded with `if not exists` / `do $$ ... $$` blocks.

begin;

-- ──────────────────────────────────────────────────────────────────────────
-- 1. near_misses — the report
-- ──────────────────────────────────────────────────────────────────────────
--
-- severity_potential: what *could* have happened, not what did. This
-- is the field that lets a triage view sort the most concerning
-- reports to the top — a slip on a wet floor that *almost* sent
-- someone over a railing into machinery is severity_potential=high
-- regardless of the lack of actual injury.

create table if not exists public.near_misses (
  id                       uuid not null primary key default gen_random_uuid(),
  tenant_id                uuid not null references public.tenants(id) on delete cascade,
  -- Auto-generated by the trigger below. Format: NM-{year}-{4-digit
  -- tenant-scoped sequence}, e.g. NM-2026-0042. Mirrors the risk
  -- module's RSK-... numbering.
  report_number            text,

  -- When the event occurred (worker may report hours / days later).
  occurred_at              timestamptz not null,
  -- When the report was filed.
  reported_at              timestamptz not null default now(),
  reported_by              uuid not null references auth.users(id),

  location                 text,
  description              text not null,
  immediate_action_taken   text,

  -- Hazard taxonomy mirrors the risks table so a near-miss can roll
  -- up into the same hazard-category dashboards.
  hazard_category          text not null check (hazard_category in (
    'physical','chemical','biological','mechanical','electrical',
    'ergonomic','psychosocial','environmental','radiological')),

  -- What *could* have happened. Same 4-band scheme as the risk
  -- module so the two surfaces share visual language.
  severity_potential       text not null check (severity_potential in (
    'low','moderate','high','extreme')),

  status                   text not null default 'new' check (status in (
    'new','triaged','investigating','closed','escalated_to_risk')),

  assigned_to              uuid references auth.users(id),

  -- Optional escalation link: when a near-miss reveals a durable
  -- hazard that needs to live in the risk register, slice-2 escalation
  -- creates a `risks` row and points this column at it. ON DELETE
  -- SET NULL so deleting a risk doesn't blow away the near-miss
  -- history.
  linked_risk_id           uuid references public.risks(id) on delete set null,

  resolved_at              timestamptz,
  resolution_notes         text,

  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  updated_by               uuid references auth.users(id),

  unique (tenant_id, report_number)
);

create index if not exists idx_near_misses_tenant
  on public.near_misses(tenant_id);
create index if not exists idx_near_misses_tenant_status
  on public.near_misses(tenant_id, status) where status <> 'closed';
create index if not exists idx_near_misses_tenant_severity
  on public.near_misses(tenant_id, severity_potential);
create index if not exists idx_near_misses_assigned
  on public.near_misses(assigned_to) where assigned_to is not null;
create index if not exists idx_near_misses_linked_risk
  on public.near_misses(linked_risk_id) where linked_risk_id is not null;

-- ──────────────────────────────────────────────────────────────────────────
-- 2. report_number generator
-- ──────────────────────────────────────────────────────────────────────────
--
-- Per-tenant per-year counter. Same pattern as risk_number_sequences
-- in migration 039 — atomic UPSERT-and-increment guarantees no two
-- concurrent inserts collide on the same number.

create table if not exists public.near_miss_number_sequences (
  tenant_id   uuid not null references public.tenants(id) on delete cascade,
  year        int  not null,
  next_value  int  not null default 1,
  primary key (tenant_id, year)
);

create or replace function public.set_near_miss_number()
  returns trigger
  language plpgsql
  security definer
  set search_path = public
as $$
declare
  v_year int;
  v_seq  int;
begin
  if new.report_number is not null then
    return new;
  end if;

  v_year := extract(year from new.created_at);

  insert into public.near_miss_number_sequences (tenant_id, year, next_value)
    values (new.tenant_id, v_year, 2)
    on conflict (tenant_id, year)
      do update set next_value = public.near_miss_number_sequences.next_value + 1
    returning next_value - 1 into v_seq;

  new.report_number := format('NM-%s-%s', v_year, lpad(v_seq::text, 4, '0'));
  return new;
end $$;

drop trigger if exists trg_set_near_miss_number on public.near_misses;
create trigger trg_set_near_miss_number
  before insert on public.near_misses
  for each row
  execute function public.set_near_miss_number();

-- ──────────────────────────────────────────────────────────────────────────
-- 3. updated_at maintenance — reuse the global helper from migration 035
-- ──────────────────────────────────────────────────────────────────────────

drop trigger if exists trg_near_misses_touch_updated_at on public.near_misses;
create trigger trg_near_misses_touch_updated_at
  before update on public.near_misses
  for each row
  execute function public.touch_updated_at();

-- ──────────────────────────────────────────────────────────────────────────
-- 4. near_miss_audit_log — append-only event store
-- ──────────────────────────────────────────────────────────────────────────
--
-- Mirrors risk_audit_log (migration 038): three-layer enforcement
-- (REVOKE + immutable trigger + SECURITY DEFINER capture trigger).

create table if not exists public.near_miss_audit_log (
  id            bigserial primary key,
  tenant_id     uuid not null references public.tenants(id) on delete cascade,
  near_miss_id  uuid not null,
  event_type    text not null check (event_type in ('insert','update','delete')),
  before_row    jsonb,
  after_row     jsonb,
  actor_id      uuid,
  actor_email   text,
  context       text,
  occurred_at   timestamptz not null default now()
);

create index if not exists idx_near_miss_audit_log_near_miss
  on public.near_miss_audit_log(near_miss_id, occurred_at desc);
create index if not exists idx_near_miss_audit_log_tenant
  on public.near_miss_audit_log(tenant_id, occurred_at desc);

-- Layer 1 — role grants.
revoke update, delete on public.near_miss_audit_log from public;
revoke update, delete on public.near_miss_audit_log from authenticated;
revoke update, delete on public.near_miss_audit_log from anon;

-- Layer 2 — immutable trigger.
create or replace function public.near_miss_audit_log_immutable()
  returns trigger
  language plpgsql
as $$
begin
  raise exception 'near_miss_audit_log is append-only (tg_op=% on row id=%)', tg_op, coalesce(old.id, new.id)
    using errcode = 'integrity_constraint_violation';
end $$;

drop trigger if exists trg_near_miss_audit_log_immutable on public.near_miss_audit_log;
create trigger trg_near_miss_audit_log_immutable
  before update or delete on public.near_miss_audit_log
  for each row
  execute function public.near_miss_audit_log_immutable();

-- Layer 3 — capture trigger on near_misses.
create or replace function public.near_misses_audit_capture()
  returns trigger
  language plpgsql
  security definer
  set search_path = public
as $$
declare
  v_actor_id    uuid;
  v_actor_email text;
  v_context     text;
begin
  v_actor_id    := nullif(current_setting('request.jwt.claims', true)::jsonb->>'sub', '')::uuid;
  v_actor_email := nullif(current_setting('request.jwt.claims', true)::jsonb->>'email', '');
  v_context     := nullif(current_setting('soteria.audit_context', true), '');

  if (tg_op = 'INSERT') then
    insert into public.near_miss_audit_log (tenant_id, near_miss_id, event_type, before_row, after_row, actor_id, actor_email, context)
      values (new.tenant_id, new.id, 'insert', null, to_jsonb(new), v_actor_id, v_actor_email, v_context);
    return new;
  elsif (tg_op = 'UPDATE') then
    insert into public.near_miss_audit_log (tenant_id, near_miss_id, event_type, before_row, after_row, actor_id, actor_email, context)
      values (new.tenant_id, new.id, 'update', to_jsonb(old), to_jsonb(new), v_actor_id, v_actor_email, v_context);
    return new;
  elsif (tg_op = 'DELETE') then
    insert into public.near_miss_audit_log (tenant_id, near_miss_id, event_type, before_row, after_row, actor_id, actor_email, context)
      values (old.tenant_id, old.id, 'delete', to_jsonb(old), null, v_actor_id, v_actor_email, v_context);
    return old;
  end if;
  return null;
end $$;

drop trigger if exists trg_near_misses_audit_capture on public.near_misses;
create trigger trg_near_misses_audit_capture
  after insert or update or delete on public.near_misses
  for each row
  execute function public.near_misses_audit_capture();

grant insert, select on public.near_miss_audit_log to authenticated;
grant usage, select on sequence public.near_miss_audit_log_id_seq to authenticated;

-- ──────────────────────────────────────────────────────────────────────────
-- 5. Row-Level Security
-- ──────────────────────────────────────────────────────────────────────────

alter table public.near_misses          enable row level security;
alter table public.near_miss_audit_log  enable row level security;

drop policy if exists near_misses_tenant_scope on public.near_misses;
create policy near_misses_tenant_scope on public.near_misses
  for all to authenticated
  using (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  )
  with check (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  );

drop policy if exists near_miss_audit_log_tenant_scope on public.near_miss_audit_log;
create policy near_miss_audit_log_tenant_scope on public.near_miss_audit_log
  for select to authenticated
  using (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  );

drop policy if exists near_miss_audit_log_tenant_insert on public.near_miss_audit_log;
create policy near_miss_audit_log_tenant_insert on public.near_miss_audit_log
  for insert to authenticated
  with check (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  );

notify pgrst, 'reload schema';

commit;
