-- Migration 043: Job Hazard Analysis (JHA) Module — schema + audit + RLS.
--
-- A JHA breaks a task into ordered steps, identifies hazards in each
-- step, and applies controls from the hierarchy of controls (same
-- taxonomy as the risk module). Required by Cal/OSHA T8 §3203 IIPP
-- §(a)(4) ("identify and evaluate workplace hazards"), OSHA Voluntary
-- Protection Program practice, and ISO 45001 6.1.2.2.
--
-- Distinct from the risks table:
--   risks               — durable hazards in the register (ongoing
--                          exposures, control coverage tracked).
--   jhas + jha_steps    — task-centric breakdown ("when our crew
--                          changes the conveyor belt, here are the
--                          5 steps and what can go wrong at each").
--
-- A hazard found during a JHA can escalate to a risk register entry
-- via the slice 4 escalation hook (similar to near-miss escalation).
--
-- Single migration: schema + audit + RLS + sequence. Mirrors the
-- migration-042 (near-miss) structure. The audit log captures
-- changes to the `jhas` row only; the child tables ride through the
-- row's updated_at.
--
-- Idempotent — guarded with `if not exists` / `do $$ ... $$`.

begin;

-- ──────────────────────────────────────────────────────────────────────────
-- 1. jhas — the analysis header
-- ──────────────────────────────────────────────────────────────────────────

create table if not exists public.jhas (
  id                       uuid not null primary key default gen_random_uuid(),
  tenant_id                uuid not null references public.tenants(id) on delete cascade,
  -- Auto-generated by the trigger below. Format: JHA-{year}-{4-digit
  -- tenant-scoped sequence}, e.g. JHA-2026-0042.
  job_number               text,

  title                    text not null,
  description              text,
  location                 text,
  -- Who performs this task. Free-form text for v1 (could become an
  -- FK to crews/roles later). Examples: "Maintenance crew",
  -- "Line 3 operator", "Contractors with hot-work permit".
  performed_by             text,
  -- How often the task is performed. Drives the review cadence
  -- recommendation downstream.
  frequency                text not null check (frequency in (
    'continuous','daily','weekly','monthly','quarterly','annually','as_needed')),

  -- Aggregated PPE list — denormalized roll-up of every PPE-level
  -- control across this JHA's hazards. Populated by the editor at
  -- save-time; can be regenerated by a maintenance script if it
  -- drifts. text[] keeps the column queryable + cheap to render
  -- on the print view without a 4-table join.
  required_ppe             text[] not null default '{}',

  status                   text not null default 'draft' check (status in (
    'draft','in_review','approved','superseded')),

  assigned_to              uuid references auth.users(id),
  reviewer                 uuid references auth.users(id),
  approver                 uuid references auth.users(id),

  approved_at              timestamptz,
  approved_by              uuid references auth.users(id),

  -- ANSI/ASSP Z490.1 + most corporate practice: review JHAs at
  -- least annually, plus on every significant process change. The
  -- next_review_date is set by the editor; a future cron can email
  -- reminders the same way the risk-review cron does.
  next_review_date         date,
  last_reviewed_at         timestamptz,
  last_reviewed_by         uuid references auth.users(id),

  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  created_by               uuid not null references auth.users(id),
  updated_by               uuid references auth.users(id),

  unique (tenant_id, job_number)
);

create index if not exists idx_jhas_tenant
  on public.jhas(tenant_id);
create index if not exists idx_jhas_tenant_status
  on public.jhas(tenant_id, status) where status <> 'superseded';
create index if not exists idx_jhas_next_review
  on public.jhas(tenant_id, next_review_date) where status = 'approved';
create index if not exists idx_jhas_assigned
  on public.jhas(assigned_to) where assigned_to is not null;

-- ──────────────────────────────────────────────────────────────────────────
-- 2. jha_steps — ordered task breakdown
-- ──────────────────────────────────────────────────────────────────────────

create table if not exists public.jha_steps (
  id              uuid not null primary key default gen_random_uuid(),
  tenant_id       uuid not null references public.tenants(id) on delete cascade,
  jha_id          uuid not null references public.jhas(id) on delete cascade,
  -- 1-indexed for natural numbering on the print/audit view. Unique
  -- within a JHA — the editor renumbers all rows on reorder so we
  -- never get gaps.
  sequence        int  not null check (sequence >= 1),
  description     text not null,
  notes           text,
  created_at      timestamptz not null default now(),
  unique (jha_id, sequence)
);

create index if not exists idx_jha_steps_jha on public.jha_steps(jha_id, sequence);

-- ──────────────────────────────────────────────────────────────────────────
-- 3. jha_hazards — hazards identified within a step
-- ──────────────────────────────────────────────────────────────────────────

create table if not exists public.jha_hazards (
  id                  uuid not null primary key default gen_random_uuid(),
  tenant_id           uuid not null references public.tenants(id) on delete cascade,
  jha_id              uuid not null references public.jhas(id) on delete cascade,
  -- step_id nullable for "general" hazards that span the whole job
  -- (housekeeping, lighting). Most rows will tie to a specific step.
  step_id             uuid references public.jha_steps(id) on delete cascade,
  hazard_category     text not null check (hazard_category in (
    'physical','chemical','biological','mechanical','electrical',
    'ergonomic','psychosocial','environmental','radiological')),
  description         text not null,
  -- Same 4-band scheme as near-miss + risk for visual symmetry.
  potential_severity  text not null check (potential_severity in (
    'low','moderate','high','extreme')),
  notes               text,
  created_at          timestamptz not null default now()
);

create index if not exists idx_jha_hazards_jha  on public.jha_hazards(jha_id);
create index if not exists idx_jha_hazards_step on public.jha_hazards(step_id) where step_id is not null;

-- ──────────────────────────────────────────────────────────────────────────
-- 4. jha_hazard_controls — controls applied to a hazard
-- ──────────────────────────────────────────────────────────────────────────
--
-- Same shape as risk_controls (migration 037): either a library FK
-- or a free-text custom_name. hierarchy_level is the authoritative
-- field; the controls_library entry (when used) supplies suggestions
-- only. PPE-alone enforcement isn't replicated here — the JHA
-- editor surfaces it as a UX warning per ISO 45001 8.1.2 but
-- doesn't block save (a JHA legitimately captures "PPE today,
-- engineering control coming Q3").

create table if not exists public.jha_hazard_controls (
  id              uuid not null primary key default gen_random_uuid(),
  tenant_id       uuid not null references public.tenants(id) on delete cascade,
  jha_id          uuid not null references public.jhas(id) on delete cascade,
  hazard_id       uuid not null references public.jha_hazards(id) on delete cascade,
  control_id      uuid references public.controls_library(id),
  custom_name     text,
  hierarchy_level text not null check (hierarchy_level in (
    'elimination','substitution','engineering','administrative','ppe')),
  notes           text,
  created_at      timestamptz not null default now(),
  check (control_id is not null or custom_name is not null)
);

create index if not exists idx_jha_hazard_controls_hazard on public.jha_hazard_controls(hazard_id);
create index if not exists idx_jha_hazard_controls_jha    on public.jha_hazard_controls(jha_id);
create index if not exists idx_jha_hazard_controls_tenant_level
  on public.jha_hazard_controls(tenant_id, hierarchy_level);

-- ──────────────────────────────────────────────────────────────────────────
-- 5. job_number generator
-- ──────────────────────────────────────────────────────────────────────────

create table if not exists public.jha_number_sequences (
  tenant_id   uuid not null references public.tenants(id) on delete cascade,
  year        int  not null,
  next_value  int  not null default 1,
  primary key (tenant_id, year)
);

create or replace function public.set_jha_number()
  returns trigger
  language plpgsql
  security definer
  set search_path = public
as $$
declare
  v_year int;
  v_seq  int;
begin
  if new.job_number is not null then
    return new;
  end if;

  v_year := extract(year from new.created_at);

  insert into public.jha_number_sequences (tenant_id, year, next_value)
    values (new.tenant_id, v_year, 2)
    on conflict (tenant_id, year)
      do update set next_value = public.jha_number_sequences.next_value + 1
    returning next_value - 1 into v_seq;

  new.job_number := format('JHA-%s-%s', v_year, lpad(v_seq::text, 4, '0'));
  return new;
end $$;

drop trigger if exists trg_set_jha_number on public.jhas;
create trigger trg_set_jha_number
  before insert on public.jhas
  for each row
  execute function public.set_jha_number();

-- ──────────────────────────────────────────────────────────────────────────
-- 6. updated_at maintenance (reuses public.touch_updated_at)
-- ──────────────────────────────────────────────────────────────────────────

drop trigger if exists trg_jhas_touch_updated_at on public.jhas;
create trigger trg_jhas_touch_updated_at
  before update on public.jhas
  for each row
  execute function public.touch_updated_at();

-- ──────────────────────────────────────────────────────────────────────────
-- 7. jha_audit_log — append-only event store for the header row
-- ──────────────────────────────────────────────────────────────────────────

create table if not exists public.jha_audit_log (
  id           bigserial primary key,
  tenant_id    uuid not null references public.tenants(id) on delete cascade,
  jha_id       uuid not null,
  event_type   text not null check (event_type in ('insert','update','delete')),
  before_row   jsonb,
  after_row    jsonb,
  actor_id     uuid,
  actor_email  text,
  context      text,
  occurred_at  timestamptz not null default now()
);

create index if not exists idx_jha_audit_log_jha
  on public.jha_audit_log(jha_id, occurred_at desc);
create index if not exists idx_jha_audit_log_tenant
  on public.jha_audit_log(tenant_id, occurred_at desc);

-- Layer 1 — role grants.
revoke update, delete on public.jha_audit_log from public;
revoke update, delete on public.jha_audit_log from authenticated;
revoke update, delete on public.jha_audit_log from anon;

-- Layer 2 — immutable trigger.
create or replace function public.jha_audit_log_immutable()
  returns trigger
  language plpgsql
as $$
begin
  raise exception 'jha_audit_log is append-only (tg_op=% on row id=%)', tg_op, coalesce(old.id, new.id)
    using errcode = 'integrity_constraint_violation';
end $$;

drop trigger if exists trg_jha_audit_log_immutable on public.jha_audit_log;
create trigger trg_jha_audit_log_immutable
  before update or delete on public.jha_audit_log
  for each row
  execute function public.jha_audit_log_immutable();

-- Layer 3 — capture trigger on jhas.
create or replace function public.jhas_audit_capture()
  returns trigger
  language plpgsql
  security definer
  set search_path = public
as $$
declare
  v_actor_id    uuid;
  v_actor_email text;
  v_context     text;
begin
  v_actor_id    := nullif(current_setting('request.jwt.claims', true)::jsonb->>'sub', '')::uuid;
  v_actor_email := nullif(current_setting('request.jwt.claims', true)::jsonb->>'email', '');
  v_context     := nullif(current_setting('soteria.audit_context', true), '');

  if (tg_op = 'INSERT') then
    insert into public.jha_audit_log (tenant_id, jha_id, event_type, before_row, after_row, actor_id, actor_email, context)
      values (new.tenant_id, new.id, 'insert', null, to_jsonb(new), v_actor_id, v_actor_email, v_context);
    return new;
  elsif (tg_op = 'UPDATE') then
    insert into public.jha_audit_log (tenant_id, jha_id, event_type, before_row, after_row, actor_id, actor_email, context)
      values (new.tenant_id, new.id, 'update', to_jsonb(old), to_jsonb(new), v_actor_id, v_actor_email, v_context);
    return new;
  elsif (tg_op = 'DELETE') then
    insert into public.jha_audit_log (tenant_id, jha_id, event_type, before_row, after_row, actor_id, actor_email, context)
      values (old.tenant_id, old.id, 'delete', to_jsonb(old), null, v_actor_id, v_actor_email, v_context);
    return old;
  end if;
  return null;
end $$;

drop trigger if exists trg_jhas_audit_capture on public.jhas;
create trigger trg_jhas_audit_capture
  after insert or update or delete on public.jhas
  for each row
  execute function public.jhas_audit_capture();

grant insert, select on public.jha_audit_log to authenticated;
grant usage, select on sequence public.jha_audit_log_id_seq to authenticated;

-- ──────────────────────────────────────────────────────────────────────────
-- 8. Row-Level Security
-- ──────────────────────────────────────────────────────────────────────────

alter table public.jhas                enable row level security;
alter table public.jha_steps           enable row level security;
alter table public.jha_hazards         enable row level security;
alter table public.jha_hazard_controls enable row level security;
alter table public.jha_audit_log       enable row level security;

drop policy if exists jhas_tenant_scope on public.jhas;
create policy jhas_tenant_scope on public.jhas
  for all to authenticated
  using (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  )
  with check (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  );

drop policy if exists jha_steps_tenant_scope on public.jha_steps;
create policy jha_steps_tenant_scope on public.jha_steps
  for all to authenticated
  using (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  )
  with check (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  );

drop policy if exists jha_hazards_tenant_scope on public.jha_hazards;
create policy jha_hazards_tenant_scope on public.jha_hazards
  for all to authenticated
  using (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  )
  with check (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  );

drop policy if exists jha_hazard_controls_tenant_scope on public.jha_hazard_controls;
create policy jha_hazard_controls_tenant_scope on public.jha_hazard_controls
  for all to authenticated
  using (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  )
  with check (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  );

drop policy if exists jha_audit_log_tenant_scope on public.jha_audit_log;
create policy jha_audit_log_tenant_scope on public.jha_audit_log
  for select to authenticated
  using (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  );

drop policy if exists jha_audit_log_tenant_insert on public.jha_audit_log;
create policy jha_audit_log_tenant_insert on public.jha_audit_log
  for insert to authenticated
  with check (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  );

notify pgrst, 'reload schema';

commit;
