-- Migration 059: Incident Reporting & Investigation Module — core table.
--
-- Unified incident table covering injury/illness, near-miss, property
-- damage, and environmental spill events. Replaces (and absorbs) the
-- near_misses table in migration 042 — see 059b for the data fold.
--
-- Why one table instead of four: every incident type goes through the
-- same downstream lifecycle (triage → classify → investigate → RCA →
-- CAPA → close), feeds the same scorecard KPIs (TRIR/DART/LTIR/severity
-- rate, near-miss-to-recordable ratio, days-since-recordable), and the
-- OSHA recordability decision tree applies to injury_illness only after
-- a unified intake. Discriminator column `incident_type` keeps the type-
-- specific UX honest without splitting the schema.
--
-- Cross-module FKs (loto/hot-work/jha/confined-space permit ids) make it
-- possible to surface "which permit preceded this fire?" during
-- investigation without an extra join table.
--
-- Multi-tenancy: tenant_id NOT NULL on every table; RLS uses the
-- standard active_tenant_id() + current_user_tenant_ids() pattern.
-- Audit log mirrors the three-layer pattern from near_miss_audit_log
-- (REVOKE + immutable trigger + SECURITY DEFINER capture).
--
-- Idempotent — guarded with `if not exists` / `do $$ ... $$` blocks.

begin;

-- ──────────────────────────────────────────────────────────────────────────
-- 1. incidents — the unified report
-- ──────────────────────────────────────────────────────────────────────────

create table if not exists public.incidents (
  id                             uuid not null primary key default gen_random_uuid(),
  tenant_id                      uuid not null references public.tenants(id) on delete cascade,

  -- Auto-generated by the trigger below. Format: INC-{year}-{4-digit
  -- tenant-scoped sequence}, e.g. INC-2026-0042.
  report_number                  text,

  -- Discriminator. Each type has slightly different downstream UX —
  -- injuries get a care_case + OSHA classification, spills get a
  -- regulatory threshold check, etc.
  incident_type                  text not null check (incident_type in (
    'injury_illness', 'near_miss', 'property_damage', 'environmental')),

  -- When the event occurred (worker may report hours / days later).
  occurred_at                    timestamptz not null,
  -- When the report was filed.
  reported_at                    timestamptz not null default now(),
  -- The auth user who filed. For anonymous QR-code reports, callers set
  -- is_anonymous=true and reported_by points at a tenant service-account
  -- user (created during onboarding) — keeps NOT NULL honest while
  -- preserving the "we don't know who filed" semantics.
  reported_by                    uuid not null references auth.users(id),
  is_anonymous                   boolean not null default false,

  -- Free-text + optional GPS. location_geo lets the body-part / heatmap
  -- reports group by area without forcing a department FK on intake.
  location_text                  text,
  -- Stored as point(lon, lat). Postgres has a built-in `point` type;
  -- we don't need PostGIS for this. Apps that need full geo can add it
  -- later via a generated column.
  location_geo                   point,

  shift                          text check (shift is null or shift in ('day','swing','night')),
  description                    text not null,
  immediate_action_taken         text,

  -- Severity model: actual is what happened, potential is what *could*
  -- have happened. Probability feeds the classification matrix.
  severity_actual                text not null default 'none' check (severity_actual in (
    'none','first_aid','medical','lost_time','fatality','catastrophic')),
  severity_potential             text check (severity_potential is null or severity_potential in (
    'low','moderate','high','extreme')),
  probability                    text check (probability is null or probability in (
    'rare','unlikely','possible','likely','almost_certain')),
  -- Cached matrix cell label, e.g. "S4xP4_high". Lookup table lives in
  -- packages/core/src/incidentClassification.ts (5x5 grid → cell + SLA).
  classification_matrix_cell     text,

  status                         text not null default 'reported' check (status in (
    'reported','triaged','investigating','pending_review','closed','reopened')),

  -- Investigation lead. The investigation team_member_ids array lives
  -- on incident_investigations (migration 062, phase 2).
  assigned_investigator          uuid references auth.users(id),

  -- Cross-module linkage — the permit / JHA that preceded the event.
  -- All ON DELETE SET NULL so deleting a permit doesn't blow away the
  -- incident history that referenced it. We don't add FK constraints
  -- to tables that may not exist in every install (jha/risk are
  -- behind feature flags) — typed as uuid only, validated in app
  -- code if the modules are enabled.
  related_loto_permit_id              uuid,
  related_hot_work_permit_id          uuid,
  related_confined_space_permit_id    uuid,
  related_jha_id                      uuid,

  -- Workers' comp claim # (free-text — every carrier has its own
  -- format). Surfaced on the care-management tab.
  workers_comp_claim_number      text,

  -- For environmental incidents — captures spill quantity + units so
  -- the regulatory-threshold check (CERCLA RQ etc.) has data to work
  -- with. NULL for non-environmental events.
  spill_substance                text,
  spill_quantity                 numeric,
  spill_quantity_unit            text check (spill_quantity_unit is null or spill_quantity_unit in (
    'gal','lb','kg','L','m3')),

  -- Soft link to the legacy near_misses row this incident was migrated
  -- from (see 059b). Lets the UI show "this was originally near-miss
  -- NM-2025-0017" if needed; null for new incidents.
  legacy_near_miss_id            uuid,

  closed_at                      timestamptz,
  closed_by                      uuid references auth.users(id),

  created_at                     timestamptz not null default now(),
  updated_at                     timestamptz not null default now(),
  updated_by                     uuid references auth.users(id),

  unique (tenant_id, report_number),

  -- Closing requires both fields together.
  check ((closed_at is null) = (closed_by is null))
);

create index if not exists idx_incidents_tenant_occurred
  on public.incidents(tenant_id, occurred_at desc);
create index if not exists idx_incidents_tenant_status
  on public.incidents(tenant_id, status) where status <> 'closed';
create index if not exists idx_incidents_tenant_type_severity
  on public.incidents(tenant_id, incident_type, severity_actual);
create index if not exists idx_incidents_assigned
  on public.incidents(assigned_investigator) where assigned_investigator is not null;
create index if not exists idx_incidents_legacy_nm
  on public.incidents(legacy_near_miss_id) where legacy_near_miss_id is not null;

-- ──────────────────────────────────────────────────────────────────────────
-- 2. report_number generator — per-tenant per-year counter.
-- ──────────────────────────────────────────────────────────────────────────

create table if not exists public.incident_number_sequences (
  tenant_id   uuid not null references public.tenants(id) on delete cascade,
  year        int  not null,
  next_value  int  not null default 1,
  primary key (tenant_id, year)
);

create or replace function public.set_incident_number()
  returns trigger
  language plpgsql
  security definer
  set search_path = public
as $$
declare
  v_year int;
  v_seq  int;
begin
  if new.report_number is not null then
    return new;
  end if;

  v_year := extract(year from new.created_at);

  insert into public.incident_number_sequences (tenant_id, year, next_value)
    values (new.tenant_id, v_year, 2)
    on conflict (tenant_id, year)
      do update set next_value = public.incident_number_sequences.next_value + 1
    returning next_value - 1 into v_seq;

  new.report_number := format('INC-%s-%s', v_year, lpad(v_seq::text, 4, '0'));
  return new;
end $$;

drop trigger if exists trg_set_incident_number on public.incidents;
create trigger trg_set_incident_number
  before insert on public.incidents
  for each row
  execute function public.set_incident_number();

-- ──────────────────────────────────────────────────────────────────────────
-- 3. updated_at maintenance — reuse the global helper.
-- ──────────────────────────────────────────────────────────────────────────

drop trigger if exists trg_incidents_touch_updated_at on public.incidents;
create trigger trg_incidents_touch_updated_at
  before update on public.incidents
  for each row
  execute function public.touch_updated_at();

-- ──────────────────────────────────────────────────────────────────────────
-- 4. incident_audit_log — append-only event store.
-- ──────────────────────────────────────────────────────────────────────────
--
-- Three-layer enforcement, mirrors near_miss_audit_log in migration 042.

create table if not exists public.incident_audit_log (
  id            bigserial primary key,
  tenant_id     uuid not null references public.tenants(id) on delete cascade,
  incident_id   uuid not null,
  event_type    text not null check (event_type in ('insert','update','delete')),
  before_row    jsonb,
  after_row     jsonb,
  actor_id      uuid,
  actor_email   text,
  context       text,
  occurred_at   timestamptz not null default now()
);

create index if not exists idx_incident_audit_log_incident
  on public.incident_audit_log(incident_id, occurred_at desc);
create index if not exists idx_incident_audit_log_tenant
  on public.incident_audit_log(tenant_id, occurred_at desc);

revoke update, delete on public.incident_audit_log from public;
revoke update, delete on public.incident_audit_log from authenticated;
revoke update, delete on public.incident_audit_log from anon;

create or replace function public.incident_audit_log_immutable()
  returns trigger
  language plpgsql
as $$
begin
  raise exception 'incident_audit_log is append-only (tg_op=% on row id=%)', tg_op, coalesce(old.id, new.id)
    using errcode = 'integrity_constraint_violation';
end $$;

drop trigger if exists trg_incident_audit_log_immutable on public.incident_audit_log;
create trigger trg_incident_audit_log_immutable
  before update or delete on public.incident_audit_log
  for each row
  execute function public.incident_audit_log_immutable();

create or replace function public.incidents_audit_capture()
  returns trigger
  language plpgsql
  security definer
  set search_path = public
as $$
declare
  v_actor_id    uuid;
  v_actor_email text;
  v_context     text;
begin
  v_actor_id    := nullif(current_setting('request.jwt.claims', true)::jsonb->>'sub', '')::uuid;
  v_actor_email := nullif(current_setting('request.jwt.claims', true)::jsonb->>'email', '');
  v_context     := nullif(current_setting('soteria.audit_context', true), '');

  if (tg_op = 'INSERT') then
    insert into public.incident_audit_log (tenant_id, incident_id, event_type, before_row, after_row, actor_id, actor_email, context)
      values (new.tenant_id, new.id, 'insert', null, to_jsonb(new), v_actor_id, v_actor_email, v_context);
    return new;
  elsif (tg_op = 'UPDATE') then
    insert into public.incident_audit_log (tenant_id, incident_id, event_type, before_row, after_row, actor_id, actor_email, context)
      values (new.tenant_id, new.id, 'update', to_jsonb(old), to_jsonb(new), v_actor_id, v_actor_email, v_context);
    return new;
  elsif (tg_op = 'DELETE') then
    insert into public.incident_audit_log (tenant_id, incident_id, event_type, before_row, after_row, actor_id, actor_email, context)
      values (old.tenant_id, old.id, 'delete', to_jsonb(old), null, v_actor_id, v_actor_email, v_context);
    return old;
  end if;
  return null;
end $$;

drop trigger if exists trg_incidents_audit_capture on public.incidents;
create trigger trg_incidents_audit_capture
  after insert or update or delete on public.incidents
  for each row
  execute function public.incidents_audit_capture();

grant insert, select on public.incident_audit_log to authenticated;
grant usage, select on sequence public.incident_audit_log_id_seq to authenticated;

-- ──────────────────────────────────────────────────────────────────────────
-- 5. Row-Level Security
-- ──────────────────────────────────────────────────────────────────────────

alter table public.incidents              enable row level security;
alter table public.incident_audit_log     enable row level security;
alter table public.incident_number_sequences enable row level security;

drop policy if exists incidents_tenant_scope on public.incidents;
create policy incidents_tenant_scope on public.incidents
  for all to authenticated
  using (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  )
  with check (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  );

drop policy if exists incident_audit_log_tenant_scope on public.incident_audit_log;
create policy incident_audit_log_tenant_scope on public.incident_audit_log
  for select to authenticated
  using (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  );

drop policy if exists incident_audit_log_tenant_insert on public.incident_audit_log;
create policy incident_audit_log_tenant_insert on public.incident_audit_log
  for insert to authenticated
  with check (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
  );

-- The sequence table is touched only by the SECURITY DEFINER trigger,
-- so we don't add an authenticated policy. Tenant-isolation is enforced
-- by the trigger logic + cascade on tenant delete.

notify pgrst, 'reload schema';

commit;
