-- Migration 138: publish the Hazardous Waste user manual.
--
-- This is an operating manual for the California-forward hazardous waste
-- module and its Expo field companion. It documents what the system can
-- prefill, where official submissions still happen, and how workers should
-- use the offline field workflow without confusing a draft with a submitted
-- compliance record.

begin;

insert into public.manuals (module_id, title, summary, body_md, published_at)
values (
  'hazardous-waste',
  'Hazardous Waste',
  'Step-by-step guide for waste determinations, accumulation checks, manifest preparation, CERS/CUPA records, calendar reminders, PDF binders, and offline Expo field use.',
  $manual$
## Overview

The Hazardous Waste module is SoteriaField's operating center for hazardous waste records, accumulation-area checks, official-form preparation, calendar reminders, and inspection binders. The module is California-forward because many customers operate under DTSC, CUPA, CalEPA/CERS, and Cal/OSHA expectations in addition to federal RCRA/EPA requirements.

The module helps the team:

1. Build a durable record for each waste stream, container, accumulation area, shipment, inspection, corrective action, and generated packet.
2. Prefill official-form preparation packets from structured data.
3. Track deadlines and aging rules before missed manifests, late inspections, and report due dates become findings.
4. Give field users an Expo mobile workflow that opens offline, keeps the checklist available without signal, and stores a local draft until it can be reviewed.

SoteriaField is a records and workflow system. It does not replace the employer's hazardous waste program, competent environmental review, legal judgment, transporter/TSDF responsibilities, or final portal submission by an authorized user.

## Compliance Scope

The module is designed around:

- Federal hazardous waste generator records under RCRA/EPA workflows.
- California hazardous waste program records under DTSC and CUPA oversight.
- CERS/Hazardous Materials Business Plan support records where hazardous waste data overlaps facility inventory and emergency planning.
- Cal/OSHA worker protection context for hazard communication, spill response, emergency action, and training evidence.
- Field inspection records for satellite accumulation areas, central accumulation areas, universal waste, used oil, and related inspection-only locations.

Always confirm applicability with your EHS leader, consultant, or counsel. Generator category, waste type, facility activity, local CUPA expectations, and state-specific rules can change what the site must do.

## Roles

- **Field worker** completes offline or online checks, flags container issues, records observations, and reports anything unsafe.
- **Area owner** corrects labels, lids, compatibility, housekeeping, access, and accumulation issues.
- **Environmental manager** approves waste determinations, reviews inspections, prepares shipments, validates reporting data, and owns calendar rules.
- **Shipping coordinator** prepares manifest data, confirms transporter/TSDF details, tracks signed copies, and resolves discrepancies.
- **Administrator** configures sites, generator profile data, roles, document templates, retention settings, and mobile access.
- **Superadmin** publishes manual updates, enables module configuration, and assists with tenant setup.

## Step 1: Set Up the Facility Profile

Before creating waste records, enter the facility information that will be reused across packets:

1. Open **Hazardous Waste**.
2. Review the facility name, physical address, mailing address, emergency phone, and primary contact.
3. Enter EPA ID numbers and any state identifiers used by the facility.
4. Add generator category assumptions for the site.
5. Add CUPA/local jurisdiction contacts and filing notes.
6. Add emergency coordinator or response contacts where your plan requires them.
7. Add standard transporter and receiving facility records only after verifying they are approved for the waste streams being shipped.
8. Save the profile and review it before every major report cycle.

Do not treat the facility profile as a one-time setup item. Review it after ownership changes, address changes, operating changes, generator category changes, emergency contact changes, or regulated-activity changes.

## Step 2: Create Waste Streams

A waste stream is the reusable record for a type of waste generated by a process. It should exist before containers and shipments are created.

1. Select **Waste Streams**.
2. Create a new stream.
3. Enter the generating process or area.
4. Describe the material clearly enough for someone outside the department to understand it.
5. Add known constituents, hazards, physical state, pH range, flash point, contaminants, and source chemicals where known.
6. Attach supporting documents such as SDS, lab results, process notes, or prior determinations.
7. Select applicable waste codes only after the environmental owner reviews the determination.
8. Assign a responsible owner and review date.
9. Save the stream as draft until it is reviewed.
10. Approve only after the determination support is complete.

Good waste stream names are specific. "Spent acetone wipe solvent from Line 2 printhead cleaning" is better than "waste solvent."

## Step 3: Document the Waste Determination

Waste determination is the decision record behind the stream. Preserve the basis for the decision, not just the final code.

1. Open the waste stream.
2. Add determination basis: generator knowledge, SDS, process knowledge, analytical result, supplier data, or prior approved profile.
3. Record ignitability, corrosivity, reactivity, toxicity, listed-waste analysis, state-only hazardous waste considerations, and any exclusions considered.
4. Attach lab reports and chain-of-custody records when used.
5. Add reviewer name, review date, and next review date.
6. Record why each selected waste code applies.
7. Record why common but non-applicable codes do not apply when that is useful for future audits.
8. Approve or return for more information.

If the process changes, review the waste determination. Do not keep using an old determination when raw materials, process chemistry, cleaning method, or waste handling changes.

## Step 4: Configure Accumulation Areas

Create every field location where waste containers can be found.

1. Open **Accumulation Areas**.
2. Add the building, room, line, lab, or yard location.
3. Select the area type: satellite accumulation, central accumulation, universal waste, used oil, or inspection-only.
4. Assign an owner and backup owner.
5. Add inspection cadence.
6. Add photo instructions and site-specific notes.
7. Identify nearby drains, eyewash, spill kit, extinguisher, emergency exits, or incompatible storage concerns.
8. Save and publish the area when ready.

For satellite accumulation areas, the area should be at or near the point of generation and under control of the operator generating the waste. For central accumulation areas, configure weekly inspections unless your site requires a stricter cadence.

## Step 5: Add Containers

Containers connect a waste stream to a physical accumulation record.

1. Open the accumulation area.
2. Add a container.
3. Select the waste stream.
4. Enter container type, size, unit, and label ID.
5. Record accumulation start date when required.
6. Add the container label status.
7. Add hazard indicators and compatibility notes.
8. Save the container.

The system should make these conditions visible:

- Container is open or not fully closed.
- Label is missing, unreadable, or incomplete.
- Accumulation start date is missing where required.
- Satellite limit is exceeded.
- Container is beyond configured accumulation time.
- Container is leaking, damaged, corroded, bulging, or incompatible.
- Secondary containment or access is inadequate.

## Step 6: Complete a Field Inspection on Web

Use web inspections when the user has a stable connection.

1. Open **Hazardous Waste → Field Inspections**.
2. Select the site and accumulation area.
3. Confirm the area owner and inspection due date.
4. Inspect each listed container.
5. Mark each check as pass, issue, not applicable, or not observed.
6. Add photos for labels, damage, leaks, open containers, blocked access, or corrected conditions.
7. Create corrective actions for findings that need follow-up.
8. Submit the inspection.
9. Review the inspection summary before leaving the area.

Inspection notes should be factual. State what was seen, where it was found, and what action was taken or requested.

## Step 7: Complete a Field Inspection in Expo Offline

The Expo mobile module is built for weak-signal areas. The field guide and checklist are bundled with the app, so they open even when the device cannot reach Supabase.

1. Open the mobile app.
2. Tap **Waste**.
3. Confirm the active tenant when the device has a session.
4. Select the area type.
5. Enter the location or accumulation area.
6. Enter the container label or ID.
7. Enter the waste description if known.
8. Complete each bundled check.
9. Flag critical conditions such as open containers, unreadable labels, leaks, incompatible storage, or satellite-limit concerns.
10. Add observations and corrective actions.
11. Tap **Save offline draft**.
12. When back online, transfer the draft into the official web inspection workflow or future sync workflow.

Important: the offline draft is a local field note. It is not a submitted compliance record until it is synchronized or entered into the official record system. The app labels it as a local draft on purpose.

## Step 8: Prepare a Manifest Packet

The system can prepare data for the Uniform Hazardous Waste Manifest, but normal generated PDFs are preparation records unless produced through an official EPA-approved workflow.

1. Open the waste shipment.
2. Confirm generator site and EPA ID.
3. Select transporter records.
4. Select receiving facility/TSDF.
5. Select waste streams and containers.
6. Confirm DOT shipping description, waste codes, quantity, container count, units, emergency phone, and special handling notes.
7. Generate the manifest preparation packet.
8. Review against current EPA/state instructions.
9. Use EPA e-Manifest or approved manifest paper/workflow for the official shipping document.
10. Store the final signed copies and return copies in the shipment record.

The module should never imply that a generic PDF is a valid shipping manifest by itself. Shipping manifests must follow EPA e-Manifest or approved registered-printer paper requirements.

## Step 9: Track Manifest Return and Exceptions

After a shipment leaves the site:

1. Mark the shipment as shipped.
2. Record shipment date and manifest tracking number.
3. Attach the generator copy.
4. Track receipt of signed return copies.
5. Review discrepancy or exception reminders.
6. Record actions taken to obtain missing copies.
7. Attach correspondence and final copies.
8. Close the shipment only after required evidence is present.

Configure 30/45/60 day checkpoints according to generator category, state, and manifest type. California workflows may have additional copy submission expectations for non-electronic manifests.

## Step 10: Generate Official-Record Preparation Packets

The module should prefill and export these records from system data:

- **EPA Uniform Hazardous Waste Manifest Form 8700-22** preparation packet.
- **EPA Continuation Sheet Form 8700-22A** preparation packet.
- **EPA Site Identification Form 8700-12** review packet.
- **EPA Biennial Hazardous Waste Report Form 8700-13 A/B** support export.
- **California Annual Facility Report** support export where applicable.
- **CERS/HMBP hazardous materials inventory** support data where hazardous waste inventory overlaps reportable chemical inventory.
- **Emergency response and contingency plan** review packet.
- **Accumulation-area inspection forms**.
- **Container labels and satellite accumulation labels**.
- **Waste determination report**.
- **Manifest exception report packet**.
- **Manifest discrepancy packet**.
- **Training matrix and roster**.
- **CUPA/DTSC inspection binder**.

Each packet should clearly show whether it is a draft worksheet, portal-upload support file, official PDF record, or API-submission candidate.

## Electronic Submission Guidance

### EPA e-Manifest

EPA e-Manifest has official electronic workflows and developer documentation. A future integration can use EPA/RCRAInfo access, API credentials, site-manager authorization, and approved e-signing workflows to submit or sign where allowed.

Until that integration is implemented and validated, SoteriaField should generate preparation packets and store official documents uploaded by the user.

### CERS

CERS is the California Environmental Reporting System used for hazardous materials business plan and related reporting. CERS EDT uses structured exchange workflows for regulatory agencies and participating local programs. Do not assume it is a public business-submission API.

For business users, SoteriaField should prepare portal-ready data, PDFs, and attachment checklists, then direct the authorized user to complete the official CERS/CUPA submission path required by the jurisdiction.

### RCRAInfo and DTSC

RCRAInfo and DTSC workflows can change by report type, user role, and state instructions. The system should keep source data organized and generate support files, but the environmental owner remains responsible for final submission and certification.

## Calendar Rules

Configure the calendar before the first report cycle.

### Federal Biennial Hazardous Waste Report

Due every even-numbered year on March 1 for the previous odd-numbered report year when the facility is subject to reporting. Example: March 1, 2028 is the normal due date for the 2027 report year.

### California Annual Facility Report

California reporting cycles should be reviewed against DTSC instructions. Use March 1 as the default support-file deadline unless current DTSC guidance or facility-specific instructions say otherwise.

### CERS/HMBP Certification

CERS/HMBP annual certification deadlines can vary by CUPA/local jurisdiction. Use March 1 as the default reminder, then override by jurisdiction. Some local agencies publish a different annual date.

### EPCRA Tier II

Tier II reporting is normally due March 1 for prior calendar year inventory. Chemical inventory data lives primarily in the Chemical Management module, but hazardous waste data can help reconcile facility inventory and emergency planning.

### Central Accumulation Inspections

Use weekly inspection reminders by default. The system should show missed inspections, late inspections, open findings, and corrective action age.

### Satellite Accumulation Limits

Default field guideposts are 55 gallons of non-acute hazardous waste, 1 quart of liquid acute hazardous waste, 1 kg of solid acute hazardous waste, and 1 quart of extremely hazardous waste. When a limit is reached or exceeded, the container must be dated and moved according to the site's required timeframe.

### Central Accumulation Aging

Configure accumulation time limits by generator category and site rule. Common federal baselines include 90 days for large quantity generators and 180 days for small quantity generators, with a 270-day case when the destination is more than 200 miles away. California and local requirements may be more conservative.

## Cal/OSHA Worker-Protection Context

Hazardous waste records are not only environmental records. They also support worker protection.

Use the module with:

- Hazard Communication records and SDS access.
- Spill response and emergency action expectations.
- PPE and exposure-control instructions.
- Training records for employees who handle, inspect, package, or ship waste.
- HAZWOPER applicability review for cleanup, emergency response, or hazardous waste operations.
- Laboratory chemical hygiene workflows where lab waste is generated.
- Incident reporting for spills, exposures, releases, injuries, or near misses.

The system should not let a field checklist become a substitute for training. Workers need to know what they are allowed to touch, what they must not touch, when to call for help, and when to evacuate.

## Labels

Use system-generated labels only after the environmental owner approves the content.

1. Confirm waste stream name.
2. Confirm hazards.
3. Confirm accumulation start date field.
4. Confirm generator/site information if included.
5. Print labels on material appropriate for the environment.
6. Place labels where they are readable during inspection.
7. Replace labels that are damaged, unreadable, contaminated, or no longer accurate.

Never hide a label behind a wall, secondary containment lip, other containers, or equipment.

## Corrective Actions

Create a corrective action when an issue cannot be fixed immediately.

1. Open the inspection finding.
2. Assign an owner.
3. Set a due date based on severity and regulatory risk.
4. Attach photos or notes.
5. Track the action until corrected.
6. Add closeout evidence.
7. Link the closed action back to the inspection record.

Critical issues should not sit as informal notes. Open containers, active leaks, incompatible storage, blocked emergency access, and missing required labels need clear ownership.

## PDF Binder Workflow

Use PDF binders for audits, inspections, customer requests, and internal program reviews.

1. Select date range.
2. Select site, department, or accumulation area.
3. Include inspections, photos, findings, corrective actions, shipments, manifests, waste determinations, labels, and training records.
4. Generate the binder.
5. Review the table of contents.
6. Confirm sensitive notes are appropriate for the audience.
7. Store or share according to company policy.

Binders should include generated timestamp, tenant, site, date range, source modules, and record identifiers. Where record hashing is available, keep the hash page with the binder.

## Mobile Offline Expectations

The Expo field module is intentionally conservative:

- It opens without a network connection.
- It bundles the checklist and calendar reference data in the app package.
- It stores one local draft per tenant on the device.
- It does not store authentication tokens outside SecureStore.
- It does not claim a field draft is submitted.
- It avoids server writes while offline.
- It keeps the worker focused on observable field conditions.

Before relying on offline use, test the workflow at the actual site:

1. Sign in while online.
2. Open **Waste** once.
3. Turn on airplane mode.
4. Reopen the app.
5. Confirm the Waste tab loads.
6. Save a draft.
7. Turn signal back on.
8. Confirm the draft remains available.

## Troubleshooting

### The Waste tab opens but no tenant is selected

The checklist still works because it is bundled. Save the field draft, then confirm the active tenant when the device is back online before turning the note into an official record.

### The worker cannot save an offline draft

Check device storage restrictions, SecureStore availability, managed-device policies, and whether the app was recently reinstalled. If storage is blocked, record the observation through the site's backup paper process and enter it later.

### A generated form packet is missing data

Open the source record and fill in the missing facility profile, EPA ID, waste stream, container, transporter, TSDF, waste code, quantity, emergency phone, or contact field. Regenerate the packet after the source data is corrected.

### The calendar date seems wrong

Check the tenant's jurisdiction configuration. Federal defaults are only defaults. CUPA, DTSC, local agency, generator category, and facility-specific conditions can change the due date or workflow.

### The field user flagged a critical issue

Treat it as a potential program issue until reviewed. Assign an owner, correct the condition, document evidence, and determine whether reporting, spill response, or incident workflow is required.

## Related Modules

- **Chemical Management** supplies SDS, source chemical, Tier II, and inventory context.
- **Incident Reporting** captures spills, releases, exposures, injuries, and corrective actions.
- **Training Records** tracks hazardous waste, HazCom, emergency response, DOT, and site-specific training.
- **My Safety Readiness** shows whether a worker is ready for assigned hazardous waste tasks.
- **JHA** can attach waste handling hazards and controls to task steps.
- **Compliance Bundles** package records for inspectors, customers, and internal audits.

## Official References To Verify

Use current official sources before final submission or policy decisions:

- EPA e-Manifest: https://www.epa.gov/e-manifest
- EPA Uniform Hazardous Waste Manifest instructions and forms: https://www.epa.gov/hwgenerators/uniform-hazardous-waste-manifest-instructions-sample-form-and-continuation-sheet
- EPA Site Identification Form 8700-12 guidance: https://www.epa.gov/hwgenerators/how-hazardous-waste-generators-transporters-and-treatment-storage-and-disposal
- EPA Biennial Hazardous Waste Report: https://www.epa.gov/hwgenerators/biennial-hazardous-waste-report
- DTSC hazardous waste generator requirements: https://dtsc.ca.gov/hazardous-waste-generator-requirements-fact-sheet/
- DTSC satellite accumulation: https://dtsc.ca.gov/satellite-accumulation/
- CalEPA CERS business resources: https://cers.calepa.ca.gov/businesses/
- CalEPA CERS EDT information: https://cers.calepa.ca.gov/edt/
- Cal/OSHA Hazard Communication, Title 8 section 5194: https://www.dir.ca.gov/title8/5194.html
- Cal/OSHA HAZWOPER, Title 8 section 5192: https://www.dir.ca.gov/title8/5192.html
- Cal/OSHA laboratory standard, Title 8 section 5191: https://www.dir.ca.gov/title8/5191.html
$manual$,
  now()
)
on conflict (module_id) do update set
  title        = excluded.title,
  summary      = excluded.summary,
  body_md      = excluded.body_md,
  published_at = coalesce(public.manuals.published_at, now()),
  updated_at   = now()
where public.manuals.body_md like '%**Edit me.**%'
   or public.manuals.body_md = ''
   or public.manuals.published_at is null;

notify pgrst, 'reload schema';

commit;
