-- Migration 229: EM-385 Compliance — projects (USACE contracts).
--
-- EM 385-1-1 is contract-scoped, so every register item belongs to a project
-- representing a USACE contract. The app's tenant -> facility model has no
-- contract concept; this introduces one. facility_id is nullable/shared: a
-- contract may span facilities, so a NULL facility row is visible in BOTH the
-- roll-up and per-facility views (the same "shared catalog" semantics migration
-- 211 gives bucket-B rows). The RLS predicate is written by hand here (not via
-- the 211 auto-loop) so the facility_id-IS-NULL allowance is explicit.
--
-- project_number is auto-generated (CTR-YYYY-NNNN) by the same per-tenant
-- per-year sequence pattern as near_misses (migration 042). contract_number is
-- the user-entered USACE number and is kept distinct.
--
-- Idempotent.

begin;

create table if not exists public.em385_projects (
  id                uuid not null primary key default gen_random_uuid(),
  tenant_id         uuid not null references public.tenants(id) on delete cascade,
  -- Nullable + shared: a NULL facility means the contract is not pinned to one
  -- facility. ON DELETE SET NULL so retiring a facility doesn't drop the
  -- contract record.
  facility_id       uuid references public.facilities(id) on delete set null,

  -- Auto-generated by the trigger below. Format: CTR-{year}-{4-digit
  -- tenant-scoped sequence}, e.g. CTR-2026-0007.
  project_number    text,
  -- The USACE contract number as written in the contract documents.
  contract_number   text not null,
  title             text not null,
  edition           text not null check (edition in ('2024','2014')),

  gda               text,   -- Government Designated Authority / contracting officer
  prime_contractor  text,
  location          text,
  start_date        date,
  end_date          date,

  status            text not null default 'active' check (status in ('active','closed','archived')),
  ssho_name         text,   -- Site Safety and Health Officer

  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  updated_by        uuid references auth.users(id),

  unique (tenant_id, project_number),
  unique (tenant_id, contract_number)
);

create index if not exists idx_em385_projects_tenant
  on public.em385_projects(tenant_id);
create index if not exists idx_em385_projects_tenant_status
  on public.em385_projects(tenant_id, status);
create index if not exists idx_em385_projects_facility
  on public.em385_projects(facility_id) where facility_id is not null;

-- ──────────────────────────────────────────────────────────────────────────
-- project_number generator — per-tenant per-year counter (mirrors migration 042)
-- ──────────────────────────────────────────────────────────────────────────

create table if not exists public.em385_project_number_sequences (
  tenant_id   uuid not null references public.tenants(id) on delete cascade,
  year        int  not null,
  next_value  int  not null default 1,
  primary key (tenant_id, year)
);

create or replace function public.set_em385_project_number()
  returns trigger
  language plpgsql
  security definer
  set search_path = public
as $$
declare
  v_year int;
  v_seq  int;
begin
  if new.project_number is not null then
    return new;
  end if;

  v_year := extract(year from new.created_at);

  insert into public.em385_project_number_sequences (tenant_id, year, next_value)
    values (new.tenant_id, v_year, 2)
    on conflict (tenant_id, year)
      do update set next_value = public.em385_project_number_sequences.next_value + 1
    returning next_value - 1 into v_seq;

  new.project_number := format('CTR-%s-%s', v_year, lpad(v_seq::text, 4, '0'));
  return new;
end $$;

drop trigger if exists trg_set_em385_project_number on public.em385_projects;
create trigger trg_set_em385_project_number
  before insert on public.em385_projects
  for each row
  execute function public.set_em385_project_number();

drop trigger if exists trg_em385_projects_touch_updated_at on public.em385_projects;
create trigger trg_em385_projects_touch_updated_at
  before update on public.em385_projects
  for each row
  execute function public.touch_updated_at();

-- Generic CRUD audit into the shared audit_log (migration 003).
drop trigger if exists trg_audit_em385_projects on public.em385_projects;
create trigger trg_audit_em385_projects
  after insert or update or delete on public.em385_projects
  for each row
  execute function public.log_audit('id');

-- ──────────────────────────────────────────────────────────────────────────
-- Row-Level Security — tenant scope + nullable-facility allowance
-- ──────────────────────────────────────────────────────────────────────────

alter table public.em385_projects enable row level security;

drop policy if exists em385_projects_tenant_scope on public.em385_projects;
create policy em385_projects_tenant_scope on public.em385_projects
  for all to authenticated
  using (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
    and (
      public.active_facility_id() is null
      or facility_id = public.active_facility_id()
      or facility_id is null
    )
  )
  with check (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (
      tenant_id in (select public.current_user_tenant_ids())
      or public.is_superadmin()
    )
    and (
      public.active_facility_id() is null
      or facility_id = public.active_facility_id()
      or facility_id is null
    )
  );

notify pgrst, 'reload schema';

commit;
