-- Migration 276: Hazard Hunt findings.
--
-- A finding is the durable record of a hazard surfaced by a Hazard Hunt — i.e. a
-- failed / flagged response on a submitted hazard-hunt inspection. It is the
-- thing that:
--   • the EHS risk model counts (open vs. resolved findings drive the
--     "proactive hazard hunting" leading indicator — see incidentRiskModel.ts),
--   • escalates into the risk register (risks.source='hazard_hunt' +
--     source_ref_id = finding id — the soft-FK pattern from migration 037),
--   • the Certified Safety Professional agent writes up.
--
-- Why a new table instead of reusing incident_actions / incident_capas: both of
-- those (migrations 063 / 152) require a NOT NULL incident_id FK to `incidents`.
-- A hazard-hunt finding has no parent incident. So findings carry their own
-- lifecycle (open → in_progress → closed, or → escalated) and an *optional*
-- capa_id bridge, populated only if a finding is later attached to an incident's
-- corrective-action plan. We do NOT loosen the shared CAPA FKs.
--
-- Idempotent.

begin;

-- ── finding_number generator (HHUNT-{year}-{4-digit tenant sequence}) ────────
-- Mirrors set_risk_number() from migration 039: a per-(tenant, year) counter
-- with an atomic UPSERT-and-increment so concurrent inserts never collide.

create table if not exists public.hazard_hunt_finding_sequences (
  tenant_id   uuid not null references public.tenants(id) on delete cascade,
  year        int  not null,
  next_value  int  not null default 1,
  primary key (tenant_id, year)
);

create table if not exists public.hazard_hunt_findings (
  id              uuid primary key default gen_random_uuid(),
  tenant_id       uuid not null references public.tenants(id) on delete cascade,
  -- Auto-generated by the trigger below. Format: HHUNT-{year}-{0001}.
  finding_number  text,
  -- The submitted hazard-hunt inspection this finding came from.
  inspection_id   uuid not null references public.inspections(id) on delete cascade,
  -- The specific response / template item that flagged it. Nullable so a finding
  -- can outlive an edited template (on delete set null, not cascade).
  response_id     uuid references public.inspection_responses(id) on delete set null,
  item_id         uuid references public.inspection_template_items(id) on delete set null,
  -- Shared 9-category hazard taxonomy (ISO 45001 6.1.2.1 + Cal/OSHA T8 §3203).
  -- Identical to risks.hazard_category / jha_hazards.hazard_category — NOT a new
  -- taxonomy. The category lets a finding escalate to a risk without remapping.
  hazard_category text not null check (hazard_category in (
    'physical','chemical','biological','mechanical','electrical',
    'ergonomic','psychosocial','environmental','radiological')),
  title           text not null,
  description     text not null,
  -- Inspector's severity read, used to seed the risk's inherent_severity on
  -- escalation (severityHintToInherent in packages/core/src/hazardHunt.ts).
  severity_hint   text check (severity_hint in ('low','moderate','high','extreme')),
  status          text not null default 'open' check (status in (
    'open','in_progress','closed','escalated')),
  -- Optional bridge to a formal CAPA, set only if this finding is later attached
  -- to an incident's corrective-action plan. Nullable; no code path requires it.
  capa_id         uuid references public.incident_capas(id) on delete set null,
  closed_at       timestamptz,
  created_by      uuid references public.profiles(id) on delete set null,
  updated_by      uuid references public.profiles(id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists idx_hazard_hunt_findings_tenant_status
  on public.hazard_hunt_findings(tenant_id, status, created_at desc);
create index if not exists idx_hazard_hunt_findings_inspection
  on public.hazard_hunt_findings(tenant_id, inspection_id);

create or replace function public.set_hazard_hunt_finding_number()
  returns trigger
  language plpgsql
  security definer                                       -- needs to read/update the sequence table
  set search_path = public
as $$
declare
  v_year int;
  v_seq  int;
begin
  if new.finding_number is not null then
    return new;                                          -- already set (e.g. import)
  end if;

  v_year := extract(year from new.created_at);

  insert into public.hazard_hunt_finding_sequences (tenant_id, year, next_value)
    values (new.tenant_id, v_year, 2)
    on conflict (tenant_id, year)
      do update set next_value = public.hazard_hunt_finding_sequences.next_value + 1
    returning next_value - 1 into v_seq;

  new.finding_number := format('HHUNT-%s-%s', v_year, lpad(v_seq::text, 4, '0'));
  return new;
end $$;

drop trigger if exists trg_set_hazard_hunt_finding_number on public.hazard_hunt_findings;
create trigger trg_set_hazard_hunt_finding_number
  before insert on public.hazard_hunt_findings
  for each row execute function public.set_hazard_hunt_finding_number();

-- RLS: tenant-scope (same predicate as the inspection engine, migration 193).
alter table public.hazard_hunt_findings enable row level security;
drop policy if exists hazard_hunt_findings_tenant_scope on public.hazard_hunt_findings;
create policy hazard_hunt_findings_tenant_scope on public.hazard_hunt_findings
  for all to authenticated
  using (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (tenant_id in (select public.current_user_tenant_ids()) or public.is_superadmin())
  )
  with check (
    (public.active_tenant_id() is null or tenant_id = public.active_tenant_id())
    and (tenant_id in (select public.current_user_tenant_ids()) or public.is_superadmin())
  );

drop trigger if exists trg_hazard_hunt_findings_touch on public.hazard_hunt_findings;
create trigger trg_hazard_hunt_findings_touch
  before update on public.hazard_hunt_findings
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_audit_hazard_hunt_findings on public.hazard_hunt_findings;
create trigger trg_audit_hazard_hunt_findings
  after insert or update or delete on public.hazard_hunt_findings
  for each row execute function public.log_audit('id');

notify pgrst, 'reload schema';

commit;
