// Exhaustive edge-case matrices for the authentication surface.
//
// These are combinatorial sweeps, not hand-picked examples: each matrix
// enumerates the full cross-product of the state variables a surface actually
// branches on, runs every combination through the REAL module, and asserts the
// SAFETY INVARIANTS that must hold for all of them.
//
// Why invariants rather than a table of expected outputs: an expected-output
// table for 15k rows is either generated by a copy of the implementation
// (circular — it cannot catch a bug both copies share) or unmaintainable. The
// invariants below are independent statements of what the auth system must
// never do, so they stay meaningful when the implementation changes.
//
// Violations are accumulated and asserted at the end of each matrix rather
// than via one expect() per case: 15k × N expects is slow and reports only the
// first failure, whereas a violation list shows every failing combination at
// once — which is what you need when a boundary shifts.
//
// EXECUTED_CASES is asserted at the bottom so the coverage claim is verifiable
// rather than aspirational.

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'

vi.mock('@sentry/nextjs', () => ({ captureException: vi.fn() }))

import {
  planInviteAction,
  INVITE_MAX_REMINDERS,
  INVITE_REMINDER_INTERVAL_DAYS,
  type InviteReminderState,
} from '@soteria/core/inviteReminderPlan'
import { clientIp } from '@/lib/rateLimit/clientIp'
import { checkMemoryRateLimit } from '@/lib/rateLimit/memory'
import { safeRedirect } from '@/lib/security/safeRedirect'
import {
  buildInviteUrl,
  generateInviteToken,
  hashInviteToken,
  inviteLinkTtlDays,
  verifyInviteToken,
} from '@/lib/invites/tokens'
import {
  isValidRole,
  isValidTenantNumber,
  isValidSlug,
  normalizeEmail,
} from '@soteria/core/validation/tenants'

const DAY_MS = 24 * 60 * 60 * 1000
const NOW = new Date('2026-08-27T12:00:00.000Z')

/** Every combination actually executed, asserted against the target at the end. */
let EXECUTED_CASES = 0
const countCase = () => { EXECUTED_CASES += 1 }

/** Cartesian product of the supplied value lists. */
function cross<T extends readonly (readonly unknown[])[]>(...lists: T): unknown[][] {
  return lists.reduce<unknown[][]>(
    (acc, list) => acc.flatMap(row => list.map(v => [...row, v])),
    [[]],
  )
}

// ───────────────────────────────────────────────────────────────────────────
// 1. Invite reminder cadence — the largest matrix, and the highest-stakes one:
//    a `cancel` from this planner is an RLS-level access revocation (migration
//    190 puts `invite_cancelled_at is null` inside current_user_tenant_ids()),
//    so a wrong cancel silently empties a live user's application.
// ───────────────────────────────────────────────────────────────────────────

const INVITED_OFFSETS_DAYS = [0, 0.5, 3, 6.99, 7, 7.01, 13.99, 14, 21, 27.99, 28, 34.99, 35, 60, 400]
const REMINDERS_SENT       = [0, 1, 2, 3, 4, 5]
const LAST_REMINDER_OFFSETS: Array<number | null> = [null, 0, 3, 6.99, 7, 7.01, 30]
const SIGN_IN_MODES        = ['never', 'beforeInvite', 'atInvite', 'afterInvite'] as const
const PASSWORD_SET_MODES: Array<boolean | undefined> = [undefined, false, true]
const CANCELLED_MODES      = ['none', 'cancelled'] as const

function agoIso(days: number): string {
  return new Date(NOW.getTime() - days * DAY_MS).toISOString()
}

describe('invite reminder cadence — full state matrix', () => {
  it('never revokes or nags a user who has already accepted, and never cancels early', () => {
    const violations: string[] = []

    for (const [invitedOffset, sent, reminderOffset, signIn, passwordSet, cancelled] of cross(
      INVITED_OFFSETS_DAYS, REMINDERS_SENT, LAST_REMINDER_OFFSETS,
      SIGN_IN_MODES, PASSWORD_SET_MODES, CANCELLED_MODES,
    ) as Array<[number, number, number | null, typeof SIGN_IN_MODES[number], boolean | undefined, typeof CANCELLED_MODES[number]]>) {
      countCase()

      const invitedAt = agoIso(invitedOffset)
      const lastSignInAt =
        signIn === 'never'        ? null
        : signIn === 'beforeInvite' ? agoIso(invitedOffset + 1)
        : signIn === 'atInvite'     ? invitedAt
        :                             agoIso(Math.max(0, invitedOffset - 0.5))

      const state: InviteReminderState = {
        invitedAt,
        lastSignInAt,
        passwordSet,
        remindersSent: sent,
        lastReminderAt: reminderOffset === null ? null : agoIso(reminderOffset),
        cancelledAt: cancelled === 'cancelled' ? agoIso(1) : null,
      }

      const id = `invited=${invitedOffset}d sent=${sent} lastReminder=${reminderOffset} signIn=${signIn} pwSet=${passwordSet} cancelled=${cancelled}`
      const action = planInviteAction(state, NOW)

      // The lifecycle has exactly three outcomes.
      if (!['none', 'send_reminder', 'cancel'].includes(action.kind)) {
        violations.push(`${id}: unknown kind ${action.kind}`)
        continue
      }

      // A cancelled invite is terminal — nothing may re-animate it.
      if (cancelled === 'cancelled' && action.kind !== 'none') {
        violations.push(`${id}: acted on an already-cancelled invite (${action.kind})`)
      }

      // THE safety property: a user holding a working credential must never be
      // nagged and must never have their access revoked. "Accepted" is either a
      // sign-in at/after this invite, or a password they chose themselves.
      const acceptedBySignIn = signIn === 'atInvite' || signIn === 'afterInvite'
      const accepted = acceptedBySignIn || passwordSet === true
      if (cancelled === 'none' && accepted && action.kind !== 'none') {
        violations.push(`${id}: ${action.kind} against an ACCEPTED user`)
      }

      if (action.kind === 'send_reminder') {
        const n = action.reminderNumber
        if (!Number.isInteger(n) || n < 1 || n > INVITE_MAX_REMINDERS) {
          violations.push(`${id}: reminderNumber ${n} outside 1..${INVITE_MAX_REMINDERS}`)
        }
        if (n !== sent + 1) violations.push(`${id}: reminderNumber ${n} != sent+1`)
      }

      // Never cancel before the full reminder ladder has been sent.
      if (action.kind === 'cancel' && sent < INVITE_MAX_REMINDERS) {
        violations.push(`${id}: cancelled after only ${sent} reminders`)
      }

      // Never act before a full interval has elapsed since the anchor.
      if (action.kind !== 'none') {
        const anchorOffset = reminderOffset === null ? invitedOffset : reminderOffset
        if (anchorOffset < INVITE_REMINDER_INTERVAL_DAYS) {
          violations.push(`${id}: acted ${anchorOffset}d after anchor (< ${INVITE_REMINDER_INTERVAL_DAYS}d)`)
        }
      }

      // Same input, same output — the cron re-reads this on every run.
      if (JSON.stringify(planInviteAction(state, NOW)) !== JSON.stringify(action)) {
        violations.push(`${id}: non-deterministic`)
      }
    }

    expect(violations).toEqual([])
  })

  it('holds the documented cadence at every boundary', () => {
    const base = { lastSignInAt: null, lastReminderAt: null, cancelledAt: null }
    const cases: Array<[number, number, string]> = [
      [6.99, 0, 'none'], [7, 0, 'send_reminder'], [7.01, 0, 'send_reminder'],
      [13.99, 1, 'none'], [14, 1, 'send_reminder'],
      [20.99, 2, 'none'], [21, 2, 'send_reminder'],
      [27.99, 3, 'none'], [28, 3, 'send_reminder'],
      [34.99, 4, 'none'], [35, 4, 'cancel'],
    ]
    for (const [days, sent, expected] of cases) {
      countCase()
      // Anchor on the last reminder once the ladder has started, matching the cron.
      const state: InviteReminderState = sent === 0
        ? { ...base, invitedAt: agoIso(days), remindersSent: 0 }
        : { ...base, invitedAt: agoIso(days), remindersSent: sent, lastReminderAt: agoIso(days - 7 * sent) }
      expect(planInviteAction(state, NOW).kind, `day ${days}, ${sent} sent`).toBe(expected)
    }
  })
})

describe('invite reminder cadence — degenerate and hostile inputs', () => {
  // The counter comes from a DB integer column, so these are drift/corruption
  // scenarios rather than attacker-controlled input. They matter anyway: the
  // module's own stated posture is "we can't reason about timing — do nothing
  // rather than guess", and the fail direction here is an access revocation.
  // `remindersSent` is typed `number`, and NaN is a legal `number` — a
  // corrupted or mistyped column reaches the planner without violating the
  // type. `null`/`undefined` are covered by the `?? 0` default.
  const UNREADABLE_COUNTERS: unknown[] = [NaN, Infinity, -Infinity, null, undefined]
  // Only a FINITE value is a count. A large finite one legitimately means the
  // ladder is finished; a negative one restarts it.
  const READABLE_COUNTERS: unknown[] = [-1, -100, 0, 2.7, 3.999, 4, 1e9]
  // `invitedAt` is typed `string | Date`; these are the strings a drifting or
  // partially-migrated row can actually produce.
  const HOSTILE_DATES: Array<string | null | undefined> = [
    'not-a-date', '', '   ', 'ecoacoustic', '2026-13-45T99:99:99Z', 'NaN', '0000-00-00',
  ]

  it('never cancels on an unreadable reminder counter', () => {
    const violations: string[] = []
    for (const counter of UNREADABLE_COUNTERS) {
      countCase()
      const action = planInviteAction({
        invitedAt:      agoIso(400),
        lastSignInAt:   null,
        remindersSent:  counter as number,
        lastReminderAt: null,
        cancelledAt:    null,
      }, NOW)
      // Cancelling is a revocation. An unreadable counter is not evidence that
      // four reminders were sent, so it must not license one.
      if (action.kind === 'cancel') {
        violations.push(`remindersSent=${String(counter)} → cancel on an unreadable counter`)
      }
    }
    expect(violations).toEqual([])
  })

  it('still completes the ladder for readable counters, however extreme', () => {
    for (const counter of READABLE_COUNTERS) {
      countCase()
      const action = planInviteAction({
        invitedAt:      agoIso(400),
        lastSignInAt:   null,
        remindersSent:  counter as number,
        lastReminderAt: null,
        cancelledAt:    null,
      }, NOW)
      const finished = Number(counter) >= INVITE_MAX_REMINDERS
      expect(action.kind, `remindersSent=${String(counter)}`).toBe(finished ? 'cancel' : 'send_reminder')
    }
  })

  it('does nothing when the invite timestamp is unusable', () => {
    for (const invitedAt of HOSTILE_DATES) {
      countCase()
      const action = planInviteAction({
        invitedAt:      invitedAt as string,
        lastSignInAt:   null,
        remindersSent:  0,
        lastReminderAt: null,
        cancelledAt:    null,
      }, NOW)
      expect(action.kind, `invitedAt=${String(invitedAt)}`).toBe('none')
    }
  })

  it('treats an unreadable cancellation or sign-in stamp as absent, never as licence to act early', () => {
    const violations: string[] = []
    for (const [signIn, cancelled] of cross(HOSTILE_DATES, HOSTILE_DATES) as Array<[unknown, unknown]>) {
      countCase()
      const action = planInviteAction({
        invitedAt:      agoIso(1),          // one day old: nothing is due yet
        lastSignInAt:   signIn as string,
        remindersSent:  0,
        lastReminderAt: null,
        cancelledAt:    cancelled as string,
      }, NOW)
      if (action.kind !== 'none') {
        violations.push(`signIn=${String(signIn)} cancelled=${String(cancelled)} → ${action.kind} on a 1-day-old invite`)
      }
    }
    expect(violations).toEqual([])
  })

  it('never acts on an invite dated in the future (clock skew)', () => {
    const violations: string[] = []
    for (const [skewDays, sent] of cross([0.5, 1, 7, 30, 365], REMINDERS_SENT) as Array<[number, number]>) {
      countCase()
      const action = planInviteAction({
        invitedAt:      new Date(NOW.getTime() + skewDays * DAY_MS).toISOString(),
        lastSignInAt:   null,
        remindersSent:  sent,
        lastReminderAt: null,
        cancelledAt:    null,
      }, NOW)
      if (action.kind !== 'none') {
        violations.push(`invite +${skewDays}d in the future, sent=${sent} → ${action.kind}`)
      }
    }
    expect(violations).toEqual([])
  })
})

// ───────────────────────────────────────────────────────────────────────────
// 2. Client IP attribution — the rate-limit key for every unauthenticated
//    endpoint. A caller who can choose their own key has no rate limit.
// ───────────────────────────────────────────────────────────────────────────

describe('clientIp — header precedence matrix', () => {
  const VERCEL: Array<string | null> = [null, '9.9.9.9', '  9.9.9.9  ']
  const CF:     Array<string | null> = [null, '8.8.8.8']
  const REAL:   Array<string | null> = [null, '7.7.7.7']
  const XFF:    Array<string | null> = [
    null, '', '   ', '1.1.1.1', 'spoofed, 2.2.2.2', 'a, b, 3.3.3.3', ',,,', '4.4.4.4, ',
  ]

  it('resolves by documented precedence and never returns an empty key', () => {
    const violations: string[] = []
    for (const [vercel, cf, real, xff] of cross(VERCEL, CF, REAL, XFF) as Array<[string | null, string | null, string | null, string | null]>) {
      countCase()
      const headers = new Headers()
      if (vercel !== null) headers.set('x-vercel-forwarded-for', vercel)
      if (cf     !== null) headers.set('cf-connecting-ip', cf)
      if (real   !== null) headers.set('x-real-ip', real)
      if (xff    !== null) headers.set('x-forwarded-for', xff)

      const ip = clientIp(new Request('https://x/api', { headers }))
      const id = `vercel=${vercel} cf=${cf} real=${real} xff=${xff}`

      // An empty key would collapse into one shared bucket for every caller.
      if (!ip || !ip.trim()) { violations.push(`${id}: empty ip key`); continue }

      // Platform headers win, in order, and are trimmed.
      if (vercel !== null && ip !== vercel.trim()) violations.push(`${id}: vercel header ignored (got ${ip})`)
      else if (vercel === null && cf !== null && ip !== cf.trim()) violations.push(`${id}: cf header ignored (got ${ip})`)
      else if (vercel === null && cf === null && real !== null && ip !== real.trim()) violations.push(`${id}: real-ip ignored (got ${ip})`)

      // With only XFF present, the RIGHTMOST hop is used — the leftmost is
      // caller-controlled, so reading it hands out a fresh bucket per request.
      if (vercel === null && cf === null && real === null && xff) {
        const hops = xff.split(',').map(h => h.trim()).filter(Boolean)
        if (hops.length > 0 && ip !== hops[hops.length - 1]) {
          violations.push(`${id}: expected rightmost hop ${hops[hops.length - 1]}, got ${ip}`)
        }
      }
    }
    expect(violations).toEqual([])
  })

  it('cannot be steered by a spoofed leftmost X-Forwarded-For entry', () => {
    // The attack: prepend your own value so every request lands in a new bucket.
    const real = '203.0.113.7'
    let previous: string | null = null
    for (let i = 0; i < 50; i++) {
      countCase()
      const headers = new Headers({ 'x-forwarded-for': `attacker-${i}, ${real}` })
      const ip = clientIp(new Request('https://x/api', { headers }))
      expect(ip, `spoof attempt ${i}`).toBe(real)
      if (previous !== null) expect(ip).toBe(previous)
      previous = ip
    }
  })
})

// ───────────────────────────────────────────────────────────────────────────
// 3. Rate limiter — per-process brake in front of the unauthenticated invite
//    endpoints. The contract is "at most `limit` per window", exactly.
// ───────────────────────────────────────────────────────────────────────────

describe('checkMemoryRateLimit — limit and window matrix', () => {
  beforeEach(() => { globalThis.__soteriaMemoryRateLimits = new Map() })
  afterEach(() => { globalThis.__soteriaMemoryRateLimits = new Map() })

  it('admits exactly `limit` calls per window, for every limit and burst size', () => {
    const violations: string[] = []
    for (const [limit, burst, windowMs] of cross(
      [1, 2, 3, 5, 10, 30], [1, 2, 5, 12, 40], [1_000, 60_000, 600_000],
    ) as Array<[number, number, number]>) {
      const key = `k:${limit}:${burst}:${windowMs}`
      let admitted = 0
      for (let i = 0; i < burst; i++) {
        countCase()
        if (checkMemoryRateLimit(key, limit, windowMs, 1_000_000).ok) admitted += 1
      }
      const expected = Math.min(limit, burst)
      if (admitted !== expected) {
        violations.push(`limit=${limit} burst=${burst}: admitted ${admitted}, expected ${expected}`)
      }
    }
    expect(violations).toEqual([])
  })

  it('reopens only after the window elapses, and reports a usable retry-after', () => {
    const violations: string[] = []
    for (const [limit, windowMs] of cross([1, 3, 10], [1_000, 60_000]) as Array<[number, number]>) {
      const key = `w:${limit}:${windowMs}`
      const t0 = 5_000_000
      for (let i = 0; i < limit; i++) { countCase(); checkMemoryRateLimit(key, limit, windowMs, t0) }

      // Blocked for the rest of the window, including the final millisecond.
      for (const at of [t0, t0 + 1, t0 + Math.floor(windowMs / 2), t0 + windowMs - 1]) {
        countCase()
        const r = checkMemoryRateLimit(key, limit, windowMs, at)
        if (r.ok) violations.push(`limit=${limit} window=${windowMs}: admitted at +${at - t0}ms, inside window`)
        if (!r.ok && (r.retryAfterSec ?? 0) < 1) violations.push(`limit=${limit}: retryAfterSec below 1s`)
      }

      // Open again exactly at the reset instant.
      countCase()
      if (!checkMemoryRateLimit(key, limit, windowMs, t0 + windowMs).ok) {
        violations.push(`limit=${limit} window=${windowMs}: still blocked at the reset instant`)
      }
    }
    expect(violations).toEqual([])
  })

  it('keys are isolated — one caller cannot consume another caller`s budget', () => {
    const violations: string[] = []
    for (let i = 0; i < 100; i++) {
      countCase()
      // Exhaust a neighbouring key, then confirm ours is untouched.
      checkMemoryRateLimit(`neighbour:${i}`, 1, 60_000, 1_000)
      checkMemoryRateLimit(`neighbour:${i}`, 1, 60_000, 1_000)
      if (!checkMemoryRateLimit(`mine:${i}`, 1, 60_000, 1_000).ok) {
        violations.push(`key mine:${i} was blocked by a neighbour`)
      }
    }
    expect(violations).toEqual([])
  })
})

// ───────────────────────────────────────────────────────────────────────────
// 4. Redirect guard — /login?next= carries an attacker-supplied value.
// ───────────────────────────────────────────────────────────────────────────

describe('safeRedirect — off-origin corpus', () => {
  const HOSTILE = [
    'https://evil.com', 'http://evil.com', '//evil.com', '///evil.com', '\\\\evil.com',
    '/\\evil.com', '\\/evil.com', 'https:evil.com', 'https:/evil.com',
    'javascript:alert(1)', 'JaVaScRiPt:alert(1)', 'data:text/html,<script>alert(1)</script>',
    'vbscript:msgbox(1)', 'file:///etc/passwd', 'ftp://evil.com',
    'https://user:pass@evil.com', 'https://evil.com@good.com', '//user@evil.com',
    'http://evil.com#@good.com', 'https://evil.com/?next=/safe',
    '/\tevil.com', '/\nevil.com', '/\revil.com', '//evil.com\t', '/%09/evil.com',
    'https://%65vil.com', '%2F%2Fevil.com', 'http:\\\\evil.com',
    '//evil.com/%2e%2e', 'https://evil.com:443', '//:@evil.com', 'http://', 'https://',
    '://evil.com', '////evil.com', 'https://evil.com\\@good.com',
  ]
  const SAFE = [
    '/', '/dashboard', '/admin/people/members', '/equipment/42?tab=photos',
    '/departments/dept-1#history', '/a/b/c/d', '/?x=1&y=2', '/path%20with%20space',
  ]
  const FALLBACKS = ['/', '/login', '/dashboard']

  it('never returns a value that can leave this origin', () => {
    const violations: string[] = []
    for (const [target, fallback] of cross([...HOSTILE, ...SAFE], FALLBACKS) as Array<[string, string]>) {
      countCase()
      const out = safeRedirect(target, fallback)
      // The only safe shape is a same-origin absolute path. Anything that a
      // browser could read as a scheme or an authority is a redirect off-site.
      if (!out.startsWith('/')) violations.push(`${target} → ${out} (not a rooted path)`)
      if (out.startsWith('//') || out.startsWith('/\\')) violations.push(`${target} → ${out} (protocol-relative)`)
      if (/^[a-z][a-z0-9+.-]*:/i.test(out)) violations.push(`${target} → ${out} (carries a scheme)`)
    }
    expect(violations).toEqual([])
  })

  it('preserves legitimate deep links and falls back on empty input', () => {
    for (const target of SAFE) { countCase(); expect(safeRedirect(target, '/login')).toBe(target) }
    for (const empty of [null, undefined, '']) {
      countCase()
      expect(safeRedirect(empty as string | null | undefined, '/login')).toBe('/login')
    }
  })
})

// ───────────────────────────────────────────────────────────────────────────
// 5. Invite token lifecycle — the token IS the credential for an
//    unauthenticated password-set endpoint, so classification must never
//    resolve a spent, superseded or expired token to 'valid'.
// ───────────────────────────────────────────────────────────────────────────

function fakeAdminReturning(result: { data?: unknown; error?: unknown }) {
  const chain: Record<string, unknown> = {
    select:      () => chain,
    eq:          () => chain,
    is:          () => chain,
    maybeSingle: () => Promise.resolve(result),
    then:        (f: (v: unknown) => unknown) => Promise.resolve(result).then(f),
  }
  return { from: () => chain } as never
}

describe('verifyInviteToken — lifecycle classification matrix', () => {
  const USED:       Array<string | null> = [null, '2026-08-01T00:00:00.000Z']
  const SUPERSEDED: Array<string | null> = [null, '2026-08-02T00:00:00.000Z']
  const EXPIRY = [
    ['past',   new Date(NOW.getTime() - 1000).toISOString()],
    ['now',    NOW.toISOString()],
    ['future', new Date(NOW.getTime() + 600_000).toISOString()],
  ] as const

  it('resolves to `valid` only when nothing has spent, replaced or expired the token', async () => {
    const violations: string[] = []
    vi.useFakeTimers()
    vi.setSystemTime(NOW)
    try {
      for (const [used, superseded, expiry] of cross(USED, SUPERSEDED, EXPIRY as unknown as unknown[]) as Array<[string | null, string | null, readonly [string, string]]>) {
        countCase()
        const [expiryLabel, expiresAt] = expiry
        const row = {
          id: 'TOK', user_id: 'U', tenant_id: 'T', email: 'a@b.com',
          expires_at: expiresAt, used_at: used, superseded_at: superseded,
        }
        const { status } = await verifyInviteToken(fakeAdminReturning({ data: row, error: null }), 'raw')
        const id = `used=${!!used} superseded=${!!superseded} expiry=${expiryLabel}`

        const shouldBeValid = !used && !superseded && expiryLabel === 'future'
        if (shouldBeValid && status !== 'valid') violations.push(`${id}: expected valid, got ${status}`)
        if (!shouldBeValid && status === 'valid') violations.push(`${id}: UNSPENT-CLASSIFIED a dead token as valid`)
      }

      // A missing row and a DB fault must both fail closed.
      for (const result of [{ data: null, error: null }, { data: null, error: { message: 'boom' } }]) {
        countCase()
        const { status } = await verifyInviteToken(fakeAdminReturning(result), 'raw')
        if (status === 'valid') violations.push(`lookup ${JSON.stringify(result)} resolved to valid`)
      }
    } finally {
      vi.useRealTimers()
    }
    expect(violations).toEqual([])
  })

  it('mints unguessable, URL-safe tokens whose stored form is a stable hash', () => {
    const seen = new Set<string>()
    for (let i = 0; i < 500; i++) {
      countCase()
      const { raw, hash } = generateInviteToken()
      expect(raw).toMatch(/^[A-Za-z0-9_-]{43}$/)   // 32 random bytes, base64url
      expect(hash).toBe(hashInviteToken(raw))       // deterministic
      expect(hash).toMatch(/^[0-9a-f]{64}$/)
      expect(seen.has(raw), `collision at iteration ${i}`).toBe(false)
      seen.add(raw)
      // The raw token must never be derivable from what the DB stores.
      expect(hash).not.toContain(raw)
    }
  })

  it('keeps the accept link on the app origin for every token shape', () => {
    for (const appUrl of ['https://soteriafield.app', 'https://x.vercel.app', 'http://localhost:3000']) {
      for (let i = 0; i < 20; i++) {
        countCase()
        const { raw } = generateInviteToken()
        const url = buildInviteUrl(appUrl, raw)
        expect(url.startsWith(`${appUrl}/accept-invite?token=`)).toBe(true)
        // base64url is URL-safe, so the token must survive round-tripping intact.
        expect(new URL(url).searchParams.get('token')).toBe(raw)
      }
    }
  })

  it('falls back to the default TTL for every unusable INVITE_LINK_TTL_DAYS value', () => {
    const ORIG = process.env.INVITE_LINK_TTL_DAYS
    // parseInt reads a leading integer, so '30d' → 30 and '1e400' → 1. Those
    // are misconfigurations that produce a working (if surprising) TTL, not
    // fallback cases; only values with no leading positive integer land here.
    const BAD = ['', ' ', '0', '-1', '-999', 'abc', 'NaN', 'Infinity', 'null', '  ', '0.5', '-0']
    try {
      for (const value of BAD) {
        countCase()
        process.env.INVITE_LINK_TTL_DAYS = value
        const days = inviteLinkTtlDays()
        // A non-positive or unparseable TTL would mint links that are dead on
        // arrival (or never expire). Both must degrade to the documented 14.
        expect(days, `INVITE_LINK_TTL_DAYS=${JSON.stringify(value)}`).toBe(14)
      }
      for (const [value, expected] of [['1', 1], ['7', 7], ['30', 30], ['365', 365]] as Array<[string, number]>) {
        countCase()
        process.env.INVITE_LINK_TTL_DAYS = value
        expect(inviteLinkTtlDays()).toBe(expected)
      }
    } finally {
      if (ORIG === undefined) delete process.env.INVITE_LINK_TTL_DAYS
      else process.env.INVITE_LINK_TTL_DAYS = ORIG
    }
  })
})

// ───────────────────────────────────────────────────────────────────────────
// 6. Boundary validators — these guard the /api/superadmin/[number] path
//    params and every invite email before it reaches Supabase auth.
// ───────────────────────────────────────────────────────────────────────────

describe('tenant + membership validators — hostile input corpus', () => {
  it('accepts only 4-digit tenant numbers', () => {
    const BAD = [
      '', ' ', '1', '12', '123', '12345', 'abcd', '００１２', '0001 ', ' 0001', '00-1',
      '0x01', '1e3', '+001', '-001', '1.23', '\n0001', '0001\n', 'null', 'undefined',
      '0001;DROP TABLE tenants', "0001' OR '1'='1", '../0001', '%30%30%30%31',
    ]
    for (const n of BAD) { countCase(); expect(isValidTenantNumber(n), n).toBe(false) }
    for (const n of ['0000', '0001', '9999', '1234']) { countCase(); expect(isValidTenantNumber(n), n).toBe(true) }
  })

  it('accepts only the four real membership roles', () => {
    const BAD: unknown[] = [
      'superadmin', 'Owner', 'OWNER', 'admin ', ' admin', '', null, undefined, 0, 1,
      true, false, {}, [], ['owner'], { role: 'owner' }, 'owner,admin', 'root', 'god',
      '__proto__', 'constructor', 'toString', 'hasOwnProperty',
    ]
    for (const r of BAD) { countCase(); expect(isValidRole(r), String(r)).toBe(false) }
    for (const r of ['owner', 'admin', 'member', 'viewer']) { countCase(); expect(isValidRole(r), r).toBe(true) }
  })

  it('normalizes emails and rejects the unusable ones', () => {
    // EMAIL_RE is deliberately permissive — "has the user typed something
    // shaped like an address" — with real validation left to Supabase auth. So
    // this corpus covers what the regex genuinely must reject: header
    // injection via whitespace, a missing domain part, and non-strings.
    const BAD: unknown[] = [
      '', ' ', 'plain', '@nodomain.com', 'no@domain', 'a@b', 'a b@c.com', 'a@b c.com',
      'a@@b.com', null, undefined, 42, {}, [], true, 'a@b.com extra',
      'a@b.com\r\nBcc: evil@x.com', 'a\n@b.com', 'a@b\t.com',
    ]
    for (const e of BAD) { countCase(); expect(normalizeEmail(e), JSON.stringify(e)).toBeNull() }

    for (const [input, expected] of [
      ['A@B.COM', 'a@b.com'], ['  jane@x.io  ', 'jane@x.io'], ['Jane.Doe+tag@Example.CO.UK', 'jane.doe+tag@example.co.uk'],
      // Surrounding whitespace — a trailing newline included — is stripped
      // rather than rejected, so a pasted address still provisions.
      ['a@b.com\n', 'a@b.com'], ['\t a@b.com \r\n', 'a@b.com'],
    ] as Array<[string, string]>) {
      countCase()
      expect(normalizeEmail(input)).toBe(expected)
      // Normalization must be idempotent, or a re-invite creates a second account.
      expect(normalizeEmail(expected)).toBe(expected)
    }
  })

  it('accepts only URL-safe tenant slugs', () => {
    const BAD = [
      '', 'a', 'ab', '-abc', 'abc-', 'AB-cd', 'a_b', 'a b', 'a.b', 'a/b', '../etc',
      'a'.repeat(65), 'ábc', 'a--', '--a',
    ]
    for (const s of BAD) { countCase(); expect(isValidSlug(s), s).toBe(false) }
    for (const s of ['abc', 'snak-king', 'wls-demo', 'a1b2c3', 'a'.repeat(64)]) {
      countCase()
      expect(isValidSlug(s), s).toBe(true)
    }
  })
})

// ───────────────────────────────────────────────────────────────────────────

describe('edge-case census', () => {
  it('executed the full matrix', () => {
    // Guards against a refactor silently collapsing a matrix to a handful of
    // cases while the suite still reports green.
    console.log(`\n  ▸ pure-matrix auth edge cases executed: ${EXECUTED_CASES.toLocaleString()}\n`)
    expect(EXECUTED_CASES).toBeGreaterThanOrEqual(10_000)
  })
})
