// OSHA Form 301 — Injury and Illness Incident Report.
//
// Single-page portrait. One per injured person. Layout follows the
// official 301's three-block structure (employee, treatment, event)
// + the case-info header + signature block. Drawn from scratch using
// pdfShared's WinAnsi sanitiser.

import { PDFDocument, StandardFonts, type PDFPage, type PDFFont, rgb } from 'pdf-lib'
import { sanitizeForWinAnsi, wrap, drawBrandMark } from '@/lib/pdfShared'
import { type Osha301Form } from '@soteria/core/oshaForms'

const PAGE_W = 612
const PAGE_H = 792
const MARGIN = 36

const NAVY  = rgb(0.13, 0.27, 0.53)
const SLATE = rgb(0.15, 0.18, 0.23)
const MUTED = rgb(0.45, 0.50, 0.55)
const RULE  = rgb(0.82, 0.85, 0.90)
const WHITE = rgb(1, 1, 1)
const BLACK = rgb(0, 0, 0)

interface RenderOpts {
  form:                Osha301Form
  establishmentName?:  string | null
}

export async function renderOsha301Pdf(opts: RenderOpts): Promise<Uint8Array> {
  const pdf  = await PDFDocument.create()
  const font = await pdf.embedFont(StandardFonts.Helvetica)
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold)
  const page = pdf.addPage([PAGE_W, PAGE_H])

  let y = PAGE_H - MARGIN

  // Header band. Mark-only brand glyph (no wordmark) on the
  // far-right edge; the 301 is portrait Letter (PAGE_W=612) so
  // there's no room for the wordmark alongside the form title +
  // case number. Mark-only stays recognisable without crowding.
  page.drawRectangle({ x: MARGIN, y: y - 30, width: PAGE_W - 2 * MARGIN, height: 30, color: NAVY })
  drawBrandMark({
    page, font, bold,
    x: PAGE_W - MARGIN - 18,
    y: y - 26,
    height: 14,
    tone: 'light',
    withWordmark: false,
  })
  page.drawText('OSHA Form 301 — Injury and Illness Incident Report', {
    x: MARGIN + 10, y: y - 21, size: 12, font: bold, color: WHITE,
  })
  page.drawText(opts.form.case_number, {
    x: PAGE_W - MARGIN - 140, y: y - 21, size: 11, font: bold, color: WHITE,
  })
  y -= 40

  if (opts.establishmentName) {
    page.drawText(sanitizeForWinAnsi(`Establishment: ${opts.establishmentName}`), {
      x: MARGIN, y, size: 9, font, color: MUTED,
    })
    y -= 14
  }
  y -= 4

  // ── Employee block ─────────────────────────────────────────────
  y = section(page, bold, 'Information about the employee', y)
  y = field(page, font, bold, 'Full name',  opts.form.employee_full_name,  y)
  y = field(page, font, bold, 'Address',    opts.form.employee_address,    y)
  y = pairedFields(page, font, bold,
    'Date of birth', opts.form.employee_dob,
    'Date hired',    opts.form.employee_hired_at, y)
  y = pairedFields(page, font, bold,
    'Gender',     opts.form.employee_gender,
    'Job title',  opts.form.employee_job_title, y)

  // ── Treatment block ────────────────────────────────────────────
  y -= 8
  y = section(page, bold, 'Information about the physician or other healthcare professional', y)
  y = field(page, font, bold, 'Treating physician', opts.form.treating_physician, y)
  y = field(page, font, bold, 'Treatment facility / clinic', opts.form.treatment_facility, y)
  y = pairedCheckboxes(page, font, bold,
    'Treated in emergency room?', opts.form.treated_in_emergency_room,
    'Hospitalised overnight?',     opts.form.hospitalised_overnight, y)

  // ── Event block ────────────────────────────────────────────────
  y -= 8
  y = section(page, bold, 'Information about the case', y)
  y = pairedFields(page, font, bold,
    'Date of injury or illness', opts.form.date_of_injury,
    'Time of event',             opts.form.time_of_event, y)
  y = field(page, font, bold, 'What was the employee doing just before the incident occurred?',
    opts.form.what_was_employee_doing, y, 2)
  y = field(page, font, bold, 'What happened?',           opts.form.what_happened,         y, 4)
  y = field(page, font, bold, 'Injury or illness',        opts.form.injury_or_illness,     y, 2)
  y = field(page, font, bold, 'Object / substance that directly harmed the employee',
    opts.form.what_object_substance, y, 2)
  if (opts.form.date_of_death) {
    y = field(page, font, bold, 'Date of death', opts.form.date_of_death, y)
  }

  // ── Reporter block ─────────────────────────────────────────────
  y -= 8
  y = section(page, bold, 'Completed by', y)
  y = pairedFields(page, font, bold,
    'Name',  opts.form.prepared_by_name,
    'Title', opts.form.prepared_by_title, y)
  y = pairedFields(page, font, bold,
    'Phone', opts.form.prepared_by_phone,
    'Date prepared', opts.form.prepared_at ? new Date(opts.form.prepared_at).toLocaleString() : null, y)

  // Footer.
  page.drawText('Generated by SoteriaField · Maintain on file for 5 years per 29 CFR 1904.33', {
    x: MARGIN, y: 24, size: 7, font, color: MUTED,
  })

  return await pdf.save()
}

// ──────────────────────────────────────────────────────────────────────────

function section(page: PDFPage, bold: PDFFont, title: string, y: number): number {
  page.drawRectangle({
    x: MARGIN, y: y - 18, width: PAGE_W - 2 * MARGIN, height: 18,
    color: rgb(0.93, 0.95, 0.98),
  })
  page.drawText(sanitizeForWinAnsi(title), {
    x: MARGIN + 6, y: y - 13, size: 9, font: bold, color: SLATE,
  })
  return y - 22
}

function field(page: PDFPage, font: PDFFont, bold: PDFFont, label: string,
  value: string | null, y: number, multiline: number = 1,
): number {
  const labelY = y - 9
  page.drawText(sanitizeForWinAnsi(label), { x: MARGIN, y: labelY, size: 7, font: bold, color: MUTED })
  const v = sanitizeForWinAnsi(value ?? '')
  const valueY = y - 22
  if (multiline > 1) {
    const lines = wrap(v, font, 9, PAGE_W - 2 * MARGIN - 4).slice(0, multiline)
    let cy = valueY
    for (const line of lines) {
      page.drawText(line, { x: MARGIN + 2, y: cy, size: 9, font, color: BLACK })
      cy -= 12
    }
    page.drawLine({
      start: { x: MARGIN, y: cy + 6 }, end: { x: PAGE_W - MARGIN, y: cy + 6 },
      thickness: 0.4, color: RULE,
    })
    return cy + 4
  }
  page.drawText(v, { x: MARGIN + 2, y: valueY, size: 9, font, color: BLACK })
  page.drawLine({
    start: { x: MARGIN, y: valueY - 3 }, end: { x: PAGE_W - MARGIN, y: valueY - 3 },
    thickness: 0.4, color: RULE,
  })
  return valueY - 8
}

function pairedFields(page: PDFPage, font: PDFFont, bold: PDFFont,
  l1: string, v1: string | null, l2: string, v2: string | null, y: number,
): number {
  const half = (PAGE_W - 2 * MARGIN) / 2
  const labelY = y - 9
  const valueY = y - 22
  page.drawText(sanitizeForWinAnsi(l1), { x: MARGIN,        y: labelY, size: 7, font: bold, color: MUTED })
  page.drawText(sanitizeForWinAnsi(l2), { x: MARGIN + half, y: labelY, size: 7, font: bold, color: MUTED })
  page.drawText(sanitizeForWinAnsi(v1 ?? ''), { x: MARGIN + 2,        y: valueY, size: 9, font, color: BLACK })
  page.drawText(sanitizeForWinAnsi(v2 ?? ''), { x: MARGIN + half + 2, y: valueY, size: 9, font, color: BLACK })
  page.drawLine({
    start: { x: MARGIN, y: valueY - 3 }, end: { x: MARGIN + half - 6, y: valueY - 3 },
    thickness: 0.4, color: RULE,
  })
  page.drawLine({
    start: { x: MARGIN + half, y: valueY - 3 }, end: { x: PAGE_W - MARGIN, y: valueY - 3 },
    thickness: 0.4, color: RULE,
  })
  return valueY - 8
}

function pairedCheckboxes(page: PDFPage, font: PDFFont, bold: PDFFont,
  l1: string, v1: boolean, l2: string, v2: boolean, y: number,
): number {
  const half = (PAGE_W - 2 * MARGIN) / 2
  drawCheckbox(page, font, bold, MARGIN, y - 14, l1, v1)
  drawCheckbox(page, font, bold, MARGIN + half, y - 14, l2, v2)
  return y - 22
}

function drawCheckbox(page: PDFPage, font: PDFFont, bold: PDFFont,
  x: number, y: number, label: string, checked: boolean,
) {
  page.drawRectangle({
    x, y, width: 10, height: 10, borderColor: SLATE, borderWidth: 0.6,
  })
  if (checked) {
    page.drawText('X', { x: x + 1, y: y + 1, size: 9, font: bold, color: rgb(0.6, 0.1, 0.1) })
  }
  page.drawText(sanitizeForWinAnsi(label), {
    x: x + 14, y: y + 2, size: 9, font, color: SLATE,
  })
}
