// OSHA Form 300A — Summary of Work-Related Injuries and Illnesses.
//
// Single-page portrait. The layout mirrors the published 300A
// (number boxes for case totals + day totals + injury/illness
// type counts, employment info block, signature block). Drawn from
// scratch so we control wrap + sanitisation; pdfShared's helpers
// give us the WinAnsi sanitiser + colour palette.

import { PDFDocument, StandardFonts, type PDFPage, type PDFFont, rgb } from 'pdf-lib'
import { sanitizeForWinAnsi, drawBrandMark } from '@/lib/pdfShared'
import {
  type Osha300ASummary,
  trirFromSummary,
  dartFromSummary,
} from '@soteria/core/oshaForms'

const PAGE_W = 612          // 8.5"
const PAGE_H = 792          // 11"
const MARGIN = 36

const NAVY  = rgb(0.13, 0.27, 0.53)
const SLATE = rgb(0.15, 0.18, 0.23)
const MUTED = rgb(0.45, 0.50, 0.55)
const RULE  = rgb(0.82, 0.85, 0.90)
const WHITE = rgb(1, 1, 1)

interface RenderOpts {
  summary:                  Osha300ASummary
  establishment: {
    name:                       string
    street:                     string | null
    city:                       string | null
    state:                      string | null
    zip:                        string | null
    naics_code:                 string | null
    certifying_executive_name:  string | null
    certifying_executive_title: string | null
    is_partial_year:            boolean
  }
  certified_by_name?:       string | null
  certified_at?:            string | null
}

export async function renderOsha300APdf(opts: RenderOpts): Promise<Uint8Array> {
  const pdf  = await PDFDocument.create()
  const font = await pdf.embedFont(StandardFonts.Helvetica)
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold)
  const page = pdf.addPage([PAGE_W, PAGE_H])

  let cursorY = PAGE_H - MARGIN

  // Header band with the SoteriaField brand mark on the right edge.
  page.drawRectangle({
    x: MARGIN, y: cursorY - 30, width: PAGE_W - 2 * MARGIN, height: 30, color: NAVY,
  })
  drawBrandMark({
    page, font, bold,
    x: PAGE_W - MARGIN - 110,
    y: cursorY - 26,
    height: 18,
    tone: 'light',
  })
  page.drawText('OSHA Form 300A — Summary of Work-Related Injuries and Illnesses', {
    x: MARGIN + 10, y: cursorY - 21, size: 12, font: bold, color: WHITE,
  })
  page.drawText(`Year ${opts.summary.year}`, {
    x: MARGIN + 380, y: cursorY - 21, size: 11, font: bold, color: WHITE,
  })
  cursorY -= 40

  // Establishment block.
  cursorY = drawEstablishmentBlock(page, font, bold, opts, cursorY)

  // Counts grid: G + H + I + J classification totals.
  cursorY -= 8
  cursorY = drawCountsGrid(page, font, bold, opts.summary, cursorY)

  // Day-counter row.
  cursorY -= 6
  cursorY = drawDaysRow(page, font, bold, opts.summary, cursorY)

  // Injury/illness type breakdown.
  cursorY -= 6
  cursorY = drawTypeRow(page, font, bold, opts.summary, cursorY)

  // Employment info (avg employees + total hours).
  cursorY -= 6
  cursorY = drawEmploymentBlock(page, font, bold, opts.summary, cursorY)

  // Computed rates (TRIR + DART) — not on the official 300A but useful
  // for the certifier to glance at while signing. Labelled as
  // "Reference rates" so a reader doesn't mistake it for an OSHA
  // requirement.
  cursorY -= 6
  cursorY = drawRatesBlock(page, font, bold, opts.summary, cursorY)

  // Certification block.
  cursorY -= 8
  drawCertificationBlock(page, font, bold, opts, cursorY)

  // Footer.
  page.drawText(sanitizeForWinAnsi('Generated by SoteriaField · Post-by deadline: April 30 of the following year'), {
    x: MARGIN, y: 24, size: 7, font, color: MUTED,
  })

  return await pdf.save()
}

// ──────────────────────────────────────────────────────────────────────────

function drawEstablishmentBlock(
  page: PDFPage, font: PDFFont, bold: PDFFont, opts: RenderOpts, top: number,
): number {
  const e = opts.establishment
  const lines = [
    e.name,
    [e.street].filter(Boolean).join(''),
    [e.city, e.state, e.zip].filter(Boolean).join(', '),
    e.naics_code ? `NAICS ${e.naics_code}` : null,
    e.is_partial_year ? 'Partial year (see attached note)' : null,
  ].filter(Boolean) as string[]

  page.drawText('Establishment', {
    x: MARGIN, y: top - 10, size: 8, font: bold, color: MUTED,
  })
  let y = top - 22
  for (const line of lines) {
    page.drawText(sanitizeForWinAnsi(line), { x: MARGIN, y, size: 11, font, color: SLATE })
    y -= 14
  }
  // Right side block for executive.
  const rx = PAGE_W / 2
  page.drawText('Certifying executive', {
    x: rx, y: top - 10, size: 8, font: bold, color: MUTED,
  })
  page.drawText(sanitizeForWinAnsi(e.certifying_executive_name ?? '(not set)'), {
    x: rx, y: top - 22, size: 11, font, color: SLATE,
  })
  page.drawText(sanitizeForWinAnsi(e.certifying_executive_title ?? ''), {
    x: rx, y: top - 36, size: 10, font, color: MUTED,
  })
  return y - 4
}

function drawCountsGrid(
  page: PDFPage, font: PDFFont, bold: PDFFont, s: Osha300ASummary, top: number,
): number {
  const cells: Array<{ label: string; value: number }> = [
    { label: 'G — Deaths',                 value: s.total_deaths },
    { label: 'H — Cases with days away',   value: s.total_days_away },
    { label: 'I — Cases with restriction', value: s.total_restricted },
    { label: 'J — Other recordable',       value: s.total_other_recordable },
  ]
  return drawNumberCells(page, font, bold, top, cells, 'Number of cases')
}

function drawDaysRow(
  page: PDFPage, font: PDFFont, bold: PDFFont, s: Osha300ASummary, top: number,
): number {
  const cells: Array<{ label: string; value: number }> = [
    { label: 'K — Total days away from work', value: s.total_days_away_count },
    { label: 'L — Total days of restriction', value: s.total_days_restricted_count },
  ]
  return drawNumberCells(page, font, bold, top, cells, 'Number of days')
}

function drawTypeRow(
  page: PDFPage, font: PDFFont, bold: PDFFont, s: Osha300ASummary, top: number,
): number {
  const cells: Array<{ label: string; value: number }> = [
    { label: '1 — Injuries',          value: s.by_injury_type.injury },
    { label: '2 — Skin disorders',    value: s.by_injury_type.skin_disorder },
    { label: '3 — Respiratory',       value: s.by_injury_type.respiratory },
    { label: '4 — Poisonings',        value: s.by_injury_type.poisoning },
    { label: '5 — Hearing loss',      value: s.by_injury_type.hearing_loss },
    { label: '6 — All other illness', value: s.by_injury_type.other_illness },
  ]
  return drawNumberCells(page, font, bold, top, cells, 'Injury and illness types')
}

function drawNumberCells(
  page: PDFPage, font: PDFFont, bold: PDFFont, top: number,
  cells: Array<{ label: string; value: number }>,
  caption: string,
): number {
  page.drawText(caption, {
    x: MARGIN, y: top - 10, size: 8, font: bold, color: MUTED,
  })
  const rowH = 36
  const usable = PAGE_W - 2 * MARGIN
  const cellW = usable / cells.length
  const yTop = top - 14
  for (let i = 0; i < cells.length; i++) {
    const c = cells[i]!
    const x = MARGIN + i * cellW
    page.drawRectangle({
      x, y: yTop - rowH, width: cellW, height: rowH,
      borderColor: RULE, borderWidth: 0.5,
    })
    // Big number, centered.
    const numStr = String(c.value)
    const approx = numStr.length * 18 * 0.55
    page.drawText(numStr, {
      x: x + cellW / 2 - approx / 2, y: yTop - rowH + 14,
      size: 18, font: bold, color: SLATE,
    })
    // Caption underneath.
    page.drawText(sanitizeForWinAnsi(c.label), {
      x: x + 4, y: yTop - rowH + 2, size: 7, font, color: MUTED,
    })
  }
  return yTop - rowH
}

function drawEmploymentBlock(
  page: PDFPage, font: PDFFont, bold: PDFFont, s: Osha300ASummary, top: number,
): number {
  page.drawText('Employment information', {
    x: MARGIN, y: top - 10, size: 8, font: bold, color: MUTED,
  })
  const yTop = top - 14
  const w = (PAGE_W - 2 * MARGIN) / 2
  const items = [
    { label: 'Annual average # of employees', value: String(s.annual_avg_employees) },
    { label: 'Total hours worked by all employees last year', value: String(s.total_hours_worked) },
  ]
  for (let i = 0; i < items.length; i++) {
    const it = items[i]!
    const x = MARGIN + i * w
    page.drawRectangle({
      x, y: yTop - 28, width: w, height: 28, borderColor: RULE, borderWidth: 0.5,
    })
    page.drawText(sanitizeForWinAnsi(it.label), {
      x: x + 4, y: yTop - 10, size: 8, font, color: MUTED,
    })
    page.drawText(it.value, {
      x: x + w - 80, y: yTop - 22, size: 14, font: bold, color: SLATE,
    })
  }
  return yTop - 28
}

function drawRatesBlock(
  page: PDFPage, font: PDFFont, bold: PDFFont, s: Osha300ASummary, top: number,
): number {
  page.drawText('Reference rates (computed; not part of OSHA 300A)', {
    x: MARGIN, y: top - 10, size: 7, font: bold, color: MUTED,
  })
  const trir = trirFromSummary(s)
  const dart = dartFromSummary(s)
  const yTop = top - 14
  const cells = [
    { label: 'TRIR (per 100 FTE)', value: trir == null ? '—' : trir.toFixed(2) },
    { label: 'DART (per 100 FTE)', value: dart == null ? '—' : dart.toFixed(2) },
  ]
  const w = (PAGE_W - 2 * MARGIN) / 2
  for (let i = 0; i < cells.length; i++) {
    const c = cells[i]!
    const x = MARGIN + i * w
    page.drawRectangle({
      x, y: yTop - 24, width: w, height: 24, borderColor: RULE, borderWidth: 0.5,
    })
    page.drawText(c.label, { x: x + 4, y: yTop - 10, size: 7, font, color: MUTED })
    page.drawText(c.value, { x: x + w - 80, y: yTop - 18, size: 12, font: bold, color: SLATE })
  }
  return yTop - 24
}

function drawCertificationBlock(
  page: PDFPage, font: PDFFont, bold: PDFFont, opts: RenderOpts, top: number,
) {
  page.drawText('Certification', {
    x: MARGIN, y: top - 10, size: 8, font: bold, color: MUTED,
  })
  const certText = `I certify that I have examined this document and that to the best of my knowledge the entries are true, accurate, and complete.`
  page.drawText(sanitizeForWinAnsi(certText), {
    x: MARGIN, y: top - 22, size: 9, font, color: SLATE,
  })
  page.drawLine({
    start: { x: MARGIN, y: top - 60 }, end: { x: MARGIN + 280, y: top - 60 },
    thickness: 0.5, color: SLATE,
  })
  page.drawLine({
    start: { x: PAGE_W - MARGIN - 200, y: top - 60 }, end: { x: PAGE_W - MARGIN, y: top - 60 },
    thickness: 0.5, color: SLATE,
  })
  if (opts.certified_by_name) {
    page.drawText(sanitizeForWinAnsi(opts.certified_by_name), {
      x: MARGIN + 4, y: top - 56, size: 11, font: bold, color: SLATE,
    })
  }
  if (opts.certified_at) {
    page.drawText(sanitizeForWinAnsi(new Date(opts.certified_at).toLocaleString()), {
      x: PAGE_W - MARGIN - 196, y: top - 56, size: 10, font, color: SLATE,
    })
  }
  page.drawText('Signed name', {
    x: MARGIN, y: top - 72, size: 7, font, color: MUTED,
  })
  page.drawText('Date / time', {
    x: PAGE_W - MARGIN - 200, y: top - 72, size: 7, font, color: MUTED,
  })
}
