'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, Loader2, Plus } from 'lucide-react'
import { useTenant } from '@/components/TenantProvider'
import { supabase } from '@/lib/supabase'
import type { HazardousWasteStreamRow } from '@soteria/core/hazardousWaste'

// Master list of waste streams the tenant has authored. Streams are the
// reusable record for "a type of waste generated by a process" — they
// are referenced by every container, shipment, and manifest. This page
// is the entry point for both auditing the catalog and starting a new
// stream.

const STATUS_LABEL: Record<HazardousWasteStreamRow['status'], string> = {
  draft:    'Draft',
  active:   'Active',
  archived: 'Archived',
}

const STATUS_TONE: Record<HazardousWasteStreamRow['status'], string> = {
  draft:    'bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-200',
  active:   'bg-emerald-100 text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-200',
  archived: 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300',
}

const CATEGORY_LABEL: Record<HazardousWasteStreamRow['generator_category'], string> = {
  lqg:  'LQG (90-day)',
  sqg:  'SQG (180-day)',
  vsqg: 'VSQG',
}

export default function HazardousWasteStreamsPage() {
  const { tenant } = useTenant()
  const [rows, setRows]     = useState<HazardousWasteStreamRow[] | null>(null)
  const [error, setError]   = useState<string | null>(null)
  const [filter, setFilter] = useState<'all' | 'active' | 'draft' | 'archived'>('all')

  const load = useCallback(async () => {
    if (!tenant?.id) return
    setError(null)
    const { data: { session } } = await supabase.auth.getSession()
    const headers: Record<string, string> = { 'x-active-tenant': tenant.id }
    if (session?.access_token) headers.authorization = `Bearer ${session.access_token}`

    const params = new URLSearchParams()
    if (filter !== 'all') params.set('status', filter)
    if (filter === 'archived') params.set('include_archived', 'true')

    const res = await fetch(`/api/hazardous-waste/streams?${params}`, { headers })
    const json = await res.json()
    if (!res.ok) { setError(json.error ?? 'Failed to load'); setRows([]); return }
    setRows(json.streams ?? [])
  }, [tenant?.id, filter])

  useEffect(() => { void load() }, [load])

  const counts = useMemo(() => {
    if (!rows) return { draft: 0, active: 0, archived: 0 }
    return rows.reduce(
      (acc, r) => ({ ...acc, [r.status]: acc[r.status] + 1 }),
      { draft: 0, active: 0, archived: 0 } as Record<HazardousWasteStreamRow['status'], number>,
    )
  }, [rows])

  return (
    <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-5">
      <div className="flex items-center gap-2 text-xs text-slate-500 dark:text-slate-400">
        <Link href="/hazardous-waste" className="inline-flex items-center gap-1 hover:text-slate-700 dark:hover:text-slate-200">
          <ArrowLeft className="h-3.5 w-3.5" /> Hazardous Waste
        </Link>
      </div>

      <header className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-slate-100">Waste streams</h1>
          <p className="mt-1 text-sm text-slate-600 dark:text-slate-300">
            Master records for each type of hazardous waste generated by a process. Containers attach to a stream.
          </p>
        </div>
        <Link
          href="/hazardous-waste/streams/new"
          className="inline-flex items-center gap-2 rounded-md bg-brand-navy px-3 py-2 text-sm font-semibold text-white hover:bg-brand-navy/90"
        >
          <Plus className="h-4 w-4" /> New stream
        </Link>
      </header>

      <div className="flex flex-wrap gap-2 text-xs">
        {(['all', 'active', 'draft', 'archived'] as const).map(value => (
          <button
            key={value}
            type="button"
            onClick={() => setFilter(value)}
            className={`px-3 py-1.5 rounded-md border ${
              filter === value
                ? 'bg-slate-900 text-white border-slate-900 dark:bg-slate-100 dark:text-slate-900 dark:border-slate-100'
                : 'border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800'
            }`}
          >
            {value === 'all' ? 'All' : STATUS_LABEL[value as HazardousWasteStreamRow['status']]}
            {value !== 'all' && rows ? ` (${counts[value as HazardousWasteStreamRow['status']]})` : ''}
          </button>
        ))}
      </div>

      {error && (
        <div className="rounded-md border border-red-300 bg-red-50 p-3 text-sm text-red-700 dark:border-red-800 dark:bg-red-950/30 dark:text-red-300">
          {error}
        </div>
      )}

      {rows === null && (
        <div className="flex items-center gap-2 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin" /> Loading…</div>
      )}

      {rows && rows.length === 0 && (
        <div className="rounded-md border border-dashed border-slate-300 dark:border-slate-700 p-8 text-center text-sm text-slate-500 dark:text-slate-400">
          No streams yet. <Link href="/hazardous-waste/streams/new" className="text-brand-navy underline">Create the first one</Link>.
        </div>
      )}

      {rows && rows.length > 0 && (
        <ul className="space-y-2">
          {rows.map(stream => (
            <li key={stream.id}>
              <Link
                href={`/hazardous-waste/streams/${stream.id}`}
                className="block rounded-lg border border-slate-200 dark:border-slate-800 p-4 hover:border-slate-400 dark:hover:border-slate-600 transition-colors"
              >
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div className="min-w-0">
                    <h3 className="font-semibold text-slate-900 dark:text-slate-100 truncate">{stream.name}</h3>
                    {stream.generating_process && (
                      <p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400 truncate">
                        {stream.generating_process}
                      </p>
                    )}
                  </div>
                  <span className={`shrink-0 px-2 py-0.5 rounded-full text-[11px] font-semibold ${STATUS_TONE[stream.status]}`}>
                    {STATUS_LABEL[stream.status]}
                  </span>
                </div>
                <div className="mt-2 flex flex-wrap gap-2 text-[11px] text-slate-600 dark:text-slate-400">
                  <span className="rounded bg-slate-100 dark:bg-slate-800 px-1.5 py-0.5">
                    {CATEGORY_LABEL[stream.generator_category]}{stream.long_haul ? ' · long-haul' : ''}
                  </span>
                  {stream.waste_codes.length > 0 && (
                    <span className="rounded bg-slate-100 dark:bg-slate-800 px-1.5 py-0.5">
                      Codes: {stream.waste_codes.join(', ')}
                    </span>
                  )}
                  {stream.physical_state && (
                    <span className="rounded bg-slate-100 dark:bg-slate-800 px-1.5 py-0.5">
                      {stream.physical_state}
                    </span>
                  )}
                </div>
              </Link>
            </li>
          ))}
        </ul>
      )}
    </main>
  )
}
