#!/usr/bin/env node
// Daily bug hunt — runs lint, typecheck, and tests in apps/web, then
// applies the static pattern scanners in ./patterns.mjs, then writes a
// dated markdown log to docs/bug-hunt-log/YYYY-MM-DD.md.
//
// If a prior log exists, the new log includes a `## Fixed since <date>`
// section listing patterns whose hit count dropped — that's the "log
// of bugs and fixes" requested in the daily routine.
//
// The script exits 0 even when findings exist; the workflow uploads the
// log as an artifact and opens an issue when HIGH-severity findings are
// present. Failing the workflow on every finding would create noise,
// not pressure.
//
// Usage:
//   node scripts/bug-hunt/run.mjs           # writes today's log
//   node scripts/bug-hunt/run.mjs --dry-run # prints to stdout, no write
//
// Env:
//   BUG_HUNT_DATE=2026-05-12  override the log filename (for backfills)
//   BUG_HUNT_SKIP_NPM=1       skip lint/typecheck/test (pattern scan only)

import { execSync, spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { PATTERNS } from './patterns.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const repo = resolve(here, '..', '..')
const web  = resolve(repo, 'apps/web')
const dryRun = process.argv.includes('--dry-run')
const skipNpm = process.env.BUG_HUNT_SKIP_NPM === '1'

const today = process.env.BUG_HUNT_DATE ?? new Date().toISOString().slice(0, 10)

// ─── npm checks ────────────────────────────────────────────────────────
// Each check returns { name, status: 'pass'|'fail'|'skipped', summary }.
// Failures are summarized in 1-3 lines (full output is too noisy for the
// daily log and is captured separately in the workflow artifact).

function runCheck(name, cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { cwd: web, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024, ...opts })
  if (r.status === 0) return { name, status: 'pass', summary: '' }
  const tail = (r.stdout + '\n' + r.stderr).trim().split('\n').slice(-12).join('\n')
  return { name, status: 'fail', summary: tail }
}

function runNpmChecks() {
  if (skipNpm) {
    return [
      { name: 'lint',      status: 'skipped', summary: 'BUG_HUNT_SKIP_NPM=1' },
      { name: 'typecheck', status: 'skipped', summary: 'BUG_HUNT_SKIP_NPM=1' },
      { name: 'tests',     status: 'skipped', summary: 'BUG_HUNT_SKIP_NPM=1' },
    ]
  }
  return [
    runCheck('lint',      'npx', ['--no-install', 'eslint', '.']),
    runCheck('typecheck', 'npx', ['--no-install', 'tsc', '--noEmit']),
    runCheck('tests',     'npx', ['--no-install', 'vitest', 'run', '--reporter=dot']),
  ]
}

// ─── pattern scan ──────────────────────────────────────────────────────

function runPatternScan() {
  const results = []
  for (const p of PATTERNS) {
    let hits
    try {
      hits = p.scan(repo)
    } catch (err) {
      hits = []
      results.push({ id: p.id, severity: p.severity, title: p.title, hits, error: String(err.message || err) })
      continue
    }
    results.push({ id: p.id, severity: p.severity, title: p.title, hits })
  }
  return results
}

// ─── diff against most recent prior log ────────────────────────────────

function findPriorLog() {
  const dir = resolve(repo, 'docs/bug-hunt-log')
  if (!existsSync(dir)) return null
  const names = readdirSync(dir)
    .filter(n => /^\d{4}-\d{2}-\d{2}\.md$/.test(n))
    .filter(n => n.slice(0, 10) < today)
    .sort()
  if (names.length === 0) return null
  const name = names[names.length - 1]
  return { date: name.slice(0, 10), path: resolve(dir, name), text: readFileSync(resolve(dir, name), 'utf8') }
}

// Parse the hit counts out of a prior log by reading the pattern table.
// Format: `| pattern-id | severity | <count> |` (see writeLog below).
function parseHitCounts(logText) {
  const map = new Map()
  for (const line of logText.split('\n')) {
    const m = line.match(/^\|\s*([a-z0-9-]+)\s*\|\s*(high|medium|low)\s*\|\s*(\d+)\s*\|/)
    if (m) map.set(m[1], Number(m[3]))
  }
  return map
}

// ─── markdown render ───────────────────────────────────────────────────

function renderLog({ checks, patterns, prior }) {
  const lines = []
  lines.push(`# Bug Hunt — ${today}`)
  lines.push('')
  lines.push(`Auto-generated by \`scripts/bug-hunt/run.mjs\`. Format spec:`)
  lines.push(`\`docs/bug-hunt-log/README.md\`.`)
  lines.push('')

  // Checks summary
  lines.push('## Checks')
  lines.push('')
  lines.push('| Check | Status |')
  lines.push('|---|---|')
  for (const c of checks) {
    const badge = c.status === 'pass' ? '✓ pass' : c.status === 'fail' ? '✗ fail' : '— skipped'
    lines.push(`| ${c.name} | ${badge} |`)
  }
  lines.push('')
  for (const c of checks) {
    if (c.status !== 'fail') continue
    lines.push(`### ${c.name} failure summary`)
    lines.push('```')
    lines.push(c.summary)
    lines.push('```')
    lines.push('')
  }

  // Pattern summary table
  lines.push('## Pattern findings')
  lines.push('')
  lines.push('| Pattern | Severity | Hits |')
  lines.push('|---|---|---|')
  for (const p of patterns) {
    lines.push(`| ${p.id} | ${p.severity} | ${p.hits.length} |`)
  }
  lines.push('')

  // Per-pattern detail (only when hits > 0)
  for (const p of patterns) {
    if (p.hits.length === 0) continue
    lines.push(`### ${p.id} — ${p.title}`)
    lines.push(`Severity: **${p.severity}** · Hits: **${p.hits.length}**`)
    lines.push('')
    for (const h of p.hits) {
      lines.push(`- \`${h.file}:${h.line}\` — ${h.note}`)
      lines.push('  ```')
      lines.push(`  ${h.snippet}`)
      lines.push('  ```')
    }
    lines.push('')
  }

  // Fixed since prior log
  if (prior) {
    const priorCounts = parseHitCounts(prior.text)
    const fixed = []
    const regressed = []
    for (const p of patterns) {
      const before = priorCounts.get(p.id)
      if (before === undefined) continue
      if (p.hits.length < before) fixed.push({ id: p.id, before, now: p.hits.length })
      if (p.hits.length > before) regressed.push({ id: p.id, before, now: p.hits.length })
    }
    if (fixed.length > 0) {
      lines.push(`## Fixed since ${prior.date}`)
      lines.push('')
      for (const f of fixed) {
        const delta = f.before - f.now
        lines.push(`- \`${f.id}\` — ${f.before} → ${f.now} (${delta} fewer)`)
      }
      lines.push('')
    }
    if (regressed.length > 0) {
      lines.push(`## Regressions since ${prior.date}`)
      lines.push('')
      for (const r of regressed) {
        const delta = r.now - r.before
        lines.push(`- \`${r.id}\` — ${r.before} → ${r.now} (${delta} more)`)
      }
      lines.push('')
    }
  }

  // Footer with commit + node version for reproducibility
  let sha = 'unknown'
  try { sha = execSync('git rev-parse HEAD', { cwd: repo, encoding: 'utf8' }).trim() } catch { /* ignore */ }
  lines.push('---')
  lines.push(`commit: \`${sha}\` · node: \`${process.version}\``)
  lines.push('')

  return lines.join('\n')
}

// ─── main ──────────────────────────────────────────────────────────────

function main() {
  const checks   = runNpmChecks()
  const patterns = runPatternScan()
  const prior    = findPriorLog()
  const md       = renderLog({ checks, patterns, prior })

  if (dryRun) {
    process.stdout.write(md)
    return
  }

  const outDir  = resolve(repo, 'docs/bug-hunt-log')
  mkdirSync(outDir, { recursive: true })
  const outPath = resolve(outDir, `${today}.md`)
  writeFileSync(outPath, md)
  console.log(`[bug-hunt] wrote ${outPath}`)

  const totalHigh = patterns.filter(p => p.severity === 'high').reduce((a, p) => a + p.hits.length, 0)
  const failedChecks = checks.filter(c => c.status === 'fail').length
  console.log(`[bug-hunt] high-severity hits: ${totalHigh}, failed checks: ${failedChecks}`)
}

main()
